#include "d3d11_effect.h"
#include <d3dcompiler.h>
#include <cstring>
#include <map>
#include <regex>
#include <stdexcept>

namespace edf::native {
namespace {
std::string AdaptNormalReconstruction(std::string source) {
  // BC3/DXT5 normal XY is quantized independently, so its squared length can
  // exceed one. Reconstruct the positive hemisphere at its boundary instead
  // of sending a negative radicand to SM5 sqrt. Preserve all valid inputs and
  // genuine NaNs; this is scoped to the authored normal decoder, not sqrt.
  static const std::regex helper(R"(float3\s+tex2D_DXT5N_xGxR\s*\([^)]*\)\s*\{[^{}]*\})");
  static const std::regex reconstruction(R"(N\.z\s*=\s*sqrt\s*\(\s*1\s*-\s*dot\s*\(\s*N\.xy\s*,\s*N\.xy\s*\)\s*\)\s*;)");
  std::smatch match;
  if(std::regex_search(source,match,helper)) {
    const auto body=match.str();
    if(!std::regex_search(body,reconstruction))
      throw std::runtime_error("unrecognized authored DXT5 normal reconstruction");
    const auto corrected=std::regex_replace(body,reconstruction,
      "float EdfNormalZSquared=1-dot(N.xy,N.xy); N.z=sqrt(EdfNormalZSquared<0?0:EdfNormalZSquared);");
    source.replace(size_t(match.position()),size_t(match.length()),corrected);
  }
  return source;
}
class Includes : public ID3DInclude {
 public:
  explicit Includes(std::filesystem::path root) : root_(std::move(root)) {}
  HRESULT __stdcall Open(D3D_INCLUDE_TYPE, LPCSTR name, LPCVOID, LPCVOID* data, UINT* size) noexcept override {
    try {
      // Retail source retains its build-tree spelling; the disc flattens this
      // particular include into Shader/. Other directory paths are rejected.
      const std::filesystem::path relative(std::strcmp(name, "../Common.fx") == 0 ? "Common.fx" : name);
      if (relative.empty() || relative.has_parent_path() || relative.is_absolute()) return E_FAIL;
      auto bytes = ReadSourceAsset(root_ / relative);
      if (bytes.empty()) return E_FAIL;
      if(relative=="Common.fx") {
        const auto source=AdaptNormalReconstruction(std::string(bytes.begin(),bytes.end()));
        bytes.assign(source.begin(),source.end());
      }
      const auto* key = bytes.data();
      const auto length = static_cast<UINT>(bytes.size());
      buffers_.emplace(key, std::move(bytes));
      *size = length;
      *data = key;
      return S_OK;
    } catch (...) { return E_FAIL; }
  }
  HRESULT __stdcall Close(LPCVOID data) noexcept override { buffers_.erase(data); return S_OK; }
 private:
  std::filesystem::path root_;
  std::map<const void*, std::vector<uint8_t>> buffers_;
};
}
void ValidateNativeShaderLink(const NativeShader& vertex, const NativeShader& pixel) {
  if (vertex.entry.pixel || !pixel.entry.pixel || !vertex.reflection || !pixel.reflection)
    throw std::runtime_error("invalid native shader stage pair");
  D3D11_SHADER_DESC vs{}, ps{};
  if (FAILED(vertex.reflection->GetDesc(&vs)) || FAILED(pixel.reflection->GetDesc(&ps)))
    throw std::runtime_error("cannot reflect native shader linkage");
  for (UINT i = 0; i < ps.InputParameters; ++i) {
    D3D11_SIGNATURE_PARAMETER_DESC input{};
    if (FAILED(pixel.reflection->GetInputParameterDesc(i,&input)))
      throw std::runtime_error("cannot reflect pixel input");
    if (!input.ReadWriteMask) continue;
    // These values are generated by rasterization, not vertex shader outputs.
    if (input.SystemValueType == D3D_NAME_IS_FRONT_FACE || input.SystemValueType == D3D_NAME_PRIMITIVE_ID ||
        input.SystemValueType == D3D_NAME_SAMPLE_INDEX || input.SystemValueType == D3D_NAME_COVERAGE) continue;
    bool matched = false;
    for (UINT j = 0; j < vs.OutputParameters; ++j) {
      D3D11_SIGNATURE_PARAMETER_DESC output{};
      if (FAILED(vertex.reflection->GetOutputParameterDesc(j,&output)))
        throw std::runtime_error("cannot reflect vertex output");
      if (_stricmp(input.SemanticName,output.SemanticName) || input.SemanticIndex != output.SemanticIndex) continue;
      matched = input.Register == output.Register && input.ComponentType == output.ComponentType &&
                (input.ReadWriteMask & output.Mask) == input.ReadWriteMask;
      break;
    }
    if (!matched) throw std::runtime_error("native shader varying mismatch: " + vertex.entry.name + " -> " +
                                           pixel.entry.name + " at " + input.SemanticName + std::to_string(input.SemanticIndex));
  }
}
NativeShader CompileNativeShader(ID3D11Device& device, const Effect& effect,
                                 const ShaderEntry& entry,
                                 const std::filesystem::path& source_path,bool reverse_depth) {
  NativeShader result;
  result.entry = entry;
  result.source_fingerprint=EffectSourceFingerprint(effect.source);
  result.source_bytes=effect.source.size();
  Includes includes(source_path.parent_path());
  // Common.fx guards its actual shadow sampling with this engine define.
  // Omitting it compiles successfully but silently removes shadow lighting.
  const D3D_SHADER_MACRO defines[]={{"__DX__","1"},{nullptr,nullptr}};
  Microsoft::WRL::ComPtr<ID3DBlob> errors;
  // Guest declarations may omit a tangent, supplying (0,0,0,1). Legacy
  // normalization's final multiply yields zero for 0 * infinity; SM5 yields
  // NaN. Preserve that defined zero-vector case without hiding NaN inputs or
  // changing the intrinsic for nonzero vectors. Define the macro only after
  // the wrappers so their intrinsic calls are not recursively substituted.
  std::string source=R"(
float EdfNativeNormalize(float v) { if(v*v==0) return 0; return normalize(v); }
float2 EdfNativeNormalize(float2 v) { if(dot(v,v)==0) return 0; return normalize(v); }
float3 EdfNativeNormalize(float3 v) { if(dot(v,v)==0) return 0; return normalize(v); }
float4 EdfNativeNormalize(float4 v) { if(dot(v,v)==0) return 0; return normalize(v); }
#define normalize EdfNativeNormalize
)"+AdaptNormalReconstruction(effect.source),compile_entry=entry.name;
  if (reverse_depth) {
    if (entry.pixel) throw std::runtime_error("depth reversal requires a vertex shader");
    // Preprocess first so comments, includes and macros cannot masquerade as
    // entry declarations. Support the game's typed, struct-returning entries;
    // reject other forms rather than rewriting arbitrary return statements.
    Microsoft::WRL::ComPtr<ID3DBlob> preprocessed;
    if (FAILED(D3DPreprocess(source.data(),source.size(),source_path.string().c_str(),defines,&includes,&preprocessed,&errors)))
      throw std::runtime_error("cannot preprocess reversed-depth vertex shader");
    source.assign(static_cast<const char*>(preprocessed->GetBufferPointer()),preprocessed->GetBufferSize());
    while (!source.empty() && source.back()=='\0') source.pop_back();
    if (!std::regex_match(entry.name,std::regex("[A-Za-z_][A-Za-z_0-9]*")))
      throw std::runtime_error("invalid reversed-depth entry identifier");
    std::smatch function;
    const std::regex signature("\\b([A-Za-z_][A-Za-z_0-9]*)\\s+"+entry.name+"\\s*\\(([^()]*)\\)\\s*\\{");
    if (!std::regex_search(source,function,signature)) throw std::runtime_error("unsupported reversed-depth entry signature: "+entry.name);
    const auto result_type=function[1].str(),parameters=function[2].str();
    std::smatch structure,position;
    if (!std::regex_search(source,structure,std::regex("\\bstruct\\s+"+result_type+"\\s*\\{([^{}]*)\\}")))
      throw std::runtime_error("reversed-depth entry must return a structure");
    const auto fields=structure[1].str();
    if (!std::regex_search(fields,position,std::regex("\\bfloat4\\s+([A-Za-z_][A-Za-z_0-9]*)\\s*:\\s*(?:SV_POSITION|POSITION)0?\\s*;",std::regex::icase)))
      throw std::runtime_error("reversed-depth entry needs a float4 position");
    std::string arguments;
    size_t begin=0;
    while (begin<parameters.size()) {
      auto end=parameters.find(',',begin); if (end==std::string::npos) end=parameters.size();
      const auto parameter=parameters.substr(begin,end-begin);
      std::smatch argument;
      if (!std::regex_match(parameter,argument,std::regex("\\s*(?:(?:in|uniform)\\s+)?[A-Za-z_][A-Za-z_0-9]*\\s+([A-Za-z_][A-Za-z_0-9]*)(?:\\s*:\\s*[A-Za-z_][A-Za-z_0-9]*)?(?:\\s*=\\s*[0-9]+)?\\s*")))
        throw std::runtime_error("unsupported reversed-depth entry parameter: "+parameter);
      if (!arguments.empty()) arguments+=",";
      arguments+=argument[1].str(); begin=end+1;
    }
    compile_entry="edf_native_reversed_depth_entry";
    const auto member="edf_native_result."+position[1].str();
    source+="\n"+result_type+" "+compile_entry+"("+parameters+") { "+result_type+
      " edf_native_result="+entry.name+"("+arguments+"); "+member+".z="+member+".w-"+member+
      ".z; return edf_native_result; }\n";
  }
  const char* target = entry.pixel ? "ps_5_0" : "vs_5_0";
  HRESULT hr = D3DCompile(source.data(), source.size(), source_path.string().c_str(),
                          defines, &includes, compile_entry.c_str(), target,
                          D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY | D3DCOMPILE_OPTIMIZATION_LEVEL3,
                          0, &result.bytecode, &errors);
  if (FAILED(hr)) {
    std::string message = "native compilation failed: " + source_path.filename().string() + ':' + entry.name;
    if (errors && errors->GetBufferSize()) {
      message += '\n';
      message.append(static_cast<const char*>(errors->GetBufferPointer()), errors->GetBufferSize() - 1);
    }
    throw std::runtime_error(message);
  }
  hr = D3DReflect(result.bytecode->GetBufferPointer(), result.bytecode->GetBufferSize(),
                  __uuidof(ID3D11ShaderReflection), reinterpret_cast<void**>(result.reflection.GetAddressOf()));
  if (FAILED(hr)) throw std::runtime_error("native shader reflection failed: " + entry.name);
  if (entry.pixel)
    hr = device.CreatePixelShader(result.bytecode->GetBufferPointer(), result.bytecode->GetBufferSize(), nullptr, &result.pixel);
  else
    hr = device.CreateVertexShader(result.bytecode->GetBufferPointer(), result.bytecode->GetBufferSize(), nullptr, &result.vertex);
  if (FAILED(hr)) throw std::runtime_error("native shader creation failed: " + entry.name);
  return result;
}
}  // namespace edf::native
