# Source-level regression gate, not a whole-program reachability proof.
if(NOT DEFINED SOURCE OR NOT EXISTS "${SOURCE}")
  message(FATAL_ERROR "Native hook bridge source is required")
endif()
file(READ "${SOURCE}" bridge)
foreach(address IN ITEMS 821409A0 82140E98 821512D8 8214E640
                         8213BD90 8213C410 8214EE50 8214EFF8)
  string(FIND "${bridge}" "REX_HOOK_RAW(sub_${address})" hook)
  if(hook EQUAL -1)
    message(FATAL_ERROR "Required native hook ${address} is missing")
  endif()
  string(FIND "${bridge}" "__imp__sub_${address}" legacy)
  if(NOT legacy EQUAL -1)
    message(FATAL_ERROR "Legacy original entry ${address} reintroduced in native bridge")
  endif()
endforeach()
message(STATUS "Eight native-only hook boundaries verified")

# The inline-writer extent/caller pair is valid only for this audited producer.
# Keep this distinct from the native-only hooks above: its CPU body is retained.
get_filename_component(bridge_directory "${SOURCE}" DIRECTORY)
get_filename_component(project_directory "${bridge_directory}/../.." ABSOLUTE)
file(READ "${project_directory}/generated/default/edf2017_recomp.10.cpp" generated)
string(REPLACE "\r\n" "\n" generated "${generated}")
string(FIND "${generated}" "DEFINE_REX_FUNC(sub_8242D2B0) {" begin)
if(begin LESS 0)
  message(FATAL_ERROR "Inline index writer producer missing")
endif()
string(SUBSTRING "${generated}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
  message(FATAL_ERROR "Inline index writer producer boundary missing")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "fa4a8b883fc51da5dc5a94fcabb623aa45498acff9a192ccb9b549f707e5d96f")
  message(FATAL_ERROR "Inline index writer changed; re-audit lock/store/unlock interval")
endif()
foreach(address IN ITEMS 8242D2B0 82134A78 82134AD8)
  string(FIND "${bridge}" "REX_HOOK_RAW(sub_${address})" hook)
  if(hook LESS 0)
    message(FATAL_ERROR "Inline index writer hook ${address} missing")
  endif()
endforeach()
message(STATUS "Audited six-store inline index writer fingerprint verified")

# Constant-time cache maintenance preserves the endpoint of this exact body;
# its dcbf/sync instructions currently have no generated host operation.
file(READ "${project_directory}/generated/default/edf2017_recomp.5.cpp" generated)
string(REPLACE "\r\n" "\n" generated "${generated}")
string(FIND "${generated}" "DEFINE_REX_FUNC(sub_82141AB8) {" begin)
if(begin LESS 0)
  message(FATAL_ERROR "Cache flush original missing")
endif()
string(SUBSTRING "${generated}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
  message(FATAL_ERROR "Cache flush original boundary missing")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "fea0e017e1244dd6f5c58a9d95941fcf47331c1e48c61ebcb2350ddb8b55f9ae")
  message(FATAL_ERROR "Cache flush CPU effects changed; re-audit native constant-time endpoint")
endif()
string(FIND "${bridge}" "REX_HOOK_RAW(sub_82141AB8)" hook)
if(hook LESS 0)
  message(FATAL_ERROR "Native cache flush hook missing")
endif()
message(STATUS "Native cache flush original fingerprint verified")
