# native_cvars.h gives every native cvar defined inline in native_cvars.cpp an inline accessor with its type
# and default (EDF_NATIVE_CVAR); both definitions must be the same, or the linker keeps either one.
# Checks that each `inline REXCVAR_DEFINE_<KIND>(name, default, ...)` in the .cpp has exactly one
# EDF_NATIVE_CVAR(type, name, default) in the header, with the kind's type and the same default text, and
# that the header has no other.
if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()
file(READ "${SOURCE_DIR}/src/native_graphics/bridge/native_cvars.cpp" source)
file(READ "${SOURCE_DIR}/src/native_graphics/bridge/native_cvars.h" header)
set(type_BOOL "bool")
set(type_INT32 "int32_t")
set(type_UINT32 "uint32_t")
set(type_INT64 "int64_t")
set(type_UINT64 "uint64_t")
set(type_DOUBLE "double")
set(type_STRING "std::string")
set(define_pattern "\ninline REXCVAR_DEFINE_([A-Z0-9]+)\\([ \t\n]*([a-z_0-9]+)[ \t\n]*,[ \t\n]*(\"[^\"]*\"|[^,\"]+),")
string(REGEX MATCHALL "${define_pattern}" defines "${source}")
set(count 0)
foreach(define IN LISTS defines)
  string(REGEX MATCH "${define_pattern}" _ "${define}")
  set(kind "${CMAKE_MATCH_1}")
  set(name "${CMAKE_MATCH_2}")
  string(STRIP "${CMAKE_MATCH_3}" default_text)
  if(NOT DEFINED type_${kind})
    message(FATAL_ERROR "native cvar ${name}: unknown kind ${kind}")
  endif()
  set(expected "EDF_NATIVE_CVAR(${type_${kind}}, ${name}, ${default_text});")
  string(FIND "${header}" "${expected}" at)
  if(at LESS 0)
    message(FATAL_ERROR "native_cvars.h does not declare `${expected}` (the definition in native_cvars.cpp)")
  endif()
  math(EXPR count "${count}+1")
endforeach()
string(REGEX MATCHALL "\nEDF_NATIVE_CVAR\\(" declared "${header}")
list(LENGTH declared declared_count)
if(NOT declared_count EQUAL count)
  message(FATAL_ERROR "native_cvars.h has ${declared_count} inline accessors, native_cvars.cpp ${count} inline definitions")
endif()
if(count EQUAL 0)
  message(FATAL_ERROR "no inline native cvar definitions found")
endif()
message(STATUS "${count} inline native cvar accessors match their definitions")
