# Turns the menu fonts into a C++ source of byte arrays (src/menu_fonts.h declares them).
#   cmake -DOUTPUT=<file.cpp> -DFONT_DIR=<third_party/fonts> -DHEADER=<src/menu_fonts.h>
#         -P tools/embed-fonts.cmake
if(NOT OUTPUT OR NOT FONT_DIR OR NOT HEADER)
  message(FATAL_ERROR "embed-fonts.cmake needs OUTPUT, FONT_DIR and HEADER")
endif()

set(_fonts
  "InterRegular=Inter-Regular.ttf"
  "InterSemiBold=Inter-SemiBold.ttf"
  "FontAwesomeSolid=fa-solid-900.ttf")

set(_source "// Generated by tools/embed-fonts.cmake from third_party/fonts. Do not edit.\n")
string(APPEND _source "#include \"${HEADER}\"\n\nnamespace edf::ui {\nnamespace {\n")
set(_accessors "")
foreach(_entry IN LISTS _fonts)
  string(REPLACE "=" ";" _pair "${_entry}")
  list(GET _pair 0 _name)
  list(GET _pair 1 _file)
  file(READ "${FONT_DIR}/${_file}" _hex HEX)
  string(LENGTH "${_hex}" _hex_length)
  math(EXPR _size "${_hex_length} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
  # One line per 16 bytes keeps the source readable by editors (CMake regexes have no
  # counted repetition, so the pattern is spelled out).
  string(REPEAT "0x[0-9a-f][0-9a-f]," 16 _line_pattern)
  string(REGEX REPLACE "${_line_pattern}" "\\0\n" _bytes "${_bytes}")
  string(APPEND _source "alignas(16) const unsigned char k${_name}[${_size}] = {\n${_bytes}\n};\n")
  string(APPEND _accessors "EmbeddedFont ${_name}() { return {k${_name}, sizeof(k${_name})}; }\n")
endforeach()
string(APPEND _source "}  // namespace\n\n${_accessors}\n}  // namespace edf::ui\n")

# Rewrite only on change so an unchanged font does not rebuild the game.
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" _existing)
  if(_existing STREQUAL _source)
    return()
  endif()
endif()
file(WRITE "${OUTPUT}" "${_source}")
