# Retain E950's CPU metadata updates, without allocating/copying an Xbox shader
# command. E800's CPU-only variant does not dereference the code destination.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.50.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213E950) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing shader-upload routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing shader-upload boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "8f3caec894e033a22dbe44318de91755bd8203906717e6ed0fd977f1bdea7289")
    message(FATAL_ERROR "E950 changed; re-audit native CPU/upload separation")
endif()
string(FIND "${body}" "\t// addi r4,r28,5" upload_begin)
string(FIND "${body}" "\t// cmpwi cr6,r24,0" upload_end)
if(upload_begin LESS 0 OR upload_end LESS upload_begin)
    message(FATAL_ERROR "Shader-upload CPU boundary changed")
endif()
string(SUBSTRING "${body}" 0 ${upload_begin} prefix)
string(SUBSTRING "${body}" ${upload_end} -1 suffix)
string(REPLACE "DEFINE_REX_FUNC(sub_8213E950)" "DEFINE_REX_FUNC(edf_native_shader_upload_cpu_tail)" prefix "${prefix}")
string(REPLACE "sub_8213E800(ctx, base);" "__imp__edf_native_shader_output_cpu_tail(ctx, base);" suffix "${suffix}")
string(REPLACE "sub_8213E070(ctx, base);" "// No Xbox microcode destination exists in this native path." suffix "${suffix}")
string(REPLACE "\t// rlwinm r11,r28,2,0,29\n\tctx.r11.u64 = __builtin_rotateleft64(ctx.r28.u32 | (ctx.r28.u64 << 32), 2) & 0xFFFFFFFC;\n" "" suffix "${suffix}")
string(REPLACE "\t// add r11,r11,r25\n\tctx.r11.u64 = ctx.r11.u64 + ctx.r25.u64;\n" "" suffix "${suffix}")
string(REPLACE "\t// stw r11,40(r29)\n\tREX_STORE_U32(ctx.r29.u32 + 40, ctx.r11.u32);\n" "" suffix "${suffix}")
file(WRITE "${OUTPUT}" "// Generated native shader-upload CPU tail. Do not edit.\n#include \"edf2017_funcs.50.h\"\nREX_EXTERN(__imp__edf_native_shader_output_cpu_tail);\n${prefix}\tctx.r26.u64 = 0; // No guest shader-code allocation.\n${suffix}\n")
