# E800 has a CPU output through r6. Preserve it and its original control flow,
# but remove E678/E748 calls that only rewrite Xbox shader instruction bytes.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.66.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213E800) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing shader-output routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing shader-output routine boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "73f1b0c9f7c03a2eeb0bd995ace9e569e8f237987d46683bfe81e9b35f7d7897")
    message(FATAL_ERROR "E800 changed; re-audit native CPU/microcode separation")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_8213E800)" "DEFINE_REX_FUNC(edf_native_shader_output_cpu_tail)" body "${body}")
string(REPLACE "sub_8213E678(ctx, base);" "// Native input/output layout replaces microcode patch." body "${body}")
string(REPLACE "sub_8213E748(ctx, base);" "// Native input/output layout replaces microcode patch." body "${body}")
file(WRITE "${OUTPUT}" "// Generated native shader-output CPU tail. Do not edit.\n#include \"edf2017_funcs.66.h\"\n${body}\n")
