# Preserve D298's CPU allocation/reset/error behavior. Native completion tracking
# is retired after the old-work drain and before freeing writeback storage.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.38.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213D298) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing device reset routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing device reset boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "67e6cfe703cc6d356184d5f0f9deb5f937aae8fd5385e5b701f6e690a242bd37")
    message(FATAL_ERROR "D298 changed; re-audit native reset lifecycle")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_8213D298)" "DEFINE_REX_FUNC(edf_native_device_reset)" body "${body}")
# The native C410/BD90 consumers no longer access GPU ring storage. Retain
# command storage and writeback allocation; omit only the separate ring pool.
string(FIND "${body}" "\t// cmplwi cr6,r27,0" ring_begin)
string(FIND "${body}" "loc_8213D3CC:" ring_end)
if(ring_begin LESS 0 OR ring_end LESS ring_begin)
    message(FATAL_ERROR "Missing GPU ring allocation boundary")
endif()
string(SUBSTRING "${body}" 0 ${ring_begin} ring_head)
string(SUBSTRING "${body}" ${ring_end} -1 ring_rest)
set(body "${ring_head}\tctx.r27.u64=0; // No owned or borrowed GPU ring.\n${ring_rest}")
string(REPLACE "loc_8213D3F8:\n\t// cmplwi cr6,r27,0\n\tctx.cr6.compare<uint32_t>(ctx.r27.u32, 0, ctx.xer);\n\t// beq cr6,0x8213d684\n\tif (ctx.cr6.eq) goto loc_8213D684;"
    "loc_8213D3F8: // Only command storage is required in native mode." body "${body}")
string(REPLACE "__imp__MmGetPhysicalAddress(ctx, base);" "// No GPU ring address translation." body "${body}")
string(REPLACE "loc_8213D2BC:" "loc_8213D2BC:\n\tedf_native_reset_completion_tracking(ctx, base);" body "${body}")
foreach(name VdInitializeRingBuffer VdEnableRingBufferRPtrWriteBack VdSetSystemCommandBufferGpuIdentifierAddress)
    string(REPLACE "__imp__${name}(ctx, base);" "// Native backend owns completion; no GPU ring export." body "${body}")
endforeach()
# After writeback/counter initialization, D560..D680 only builds/copies startup
# packets (including D0F8). The following branch returns success; retain it and
# the shared failure/ABI epilogue. No CPU device state lives in the removed span
# except the command cursor, which must stay at its initialized empty position.
string(FIND "${body}" "\t// lis r10,-16367" packet_begin)
string(FIND "${body}" "\t// b 0x8213d364" packet_end)
if(packet_begin LESS 0 OR packet_end LESS packet_begin)
    message(FATAL_ERROR "Missing initializer packet boundaries")
endif()
string(SUBSTRING "${body}" 0 ${packet_begin} prefix)
string(SUBSTRING "${body}" ${packet_end} -1 suffix)
set(body "${prefix}${suffix}")
set(reset_body "${body}")
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.7.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213D1C8) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing device drain routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing device drain boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "40989b9046cd618e5abfc622104936a007c28912952171fbb3ed0d6b9485f1dc")
    message(FATAL_ERROR "D1C8 changed; re-audit native drain")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_8213D1C8)" "DEFINE_REX_FUNC(edf_native_device_drain)" body "${body}")
string(FIND "${body}" "\t// lwz r10,48(r31)" packet_begin)
string(FIND "${body}" "\t// lwz r4,10780(r31)" packet_end)
string(SUBSTRING "${body}" 0 ${packet_begin} prefix)
string(SUBSTRING "${body}" ${packet_end} -1 suffix)
string(REPLACE "\t// stw r11,40(r31)\n\tREX_STORE_U32(ctx.r31.u32 + 40, ctx.r11.u32);\n" "" suffix "${suffix}")
# C928 retains the issued-fence wait (including CF60/CDC0/C788 submission),
# and the original CPU busy loop. Only the two-word packet/reservation is gone.
set(body "${prefix}\tctx.r6.s64 = 0;\n\tctx.r5.s64 = 4;\n\tctx.r3.u64 = ctx.r31.u64;\n${suffix}")
string(REPLACE "loc_8213D21C:" "loc_8213D21C:\n\tedf_native_drain_worker_signals(ctx, base);" body "${body}")
file(WRITE "${OUTPUT}" "// Generated native device reset/drain. Do not edit.\n#include \"edf2017_funcs.38.h\"\n#include \"edf2017_funcs.7.h\"\nREX_EXTERN(edf_native_reset_completion_tracking);\nREX_EXTERN(edf_native_drain_worker_signals);\n${reset_body}\n${body}\n")
