# Preserve CPU/header/ABI effects; dispatch no retail buffer/cache helper.
set(result "// Generated native buffer unlock chain. Do not edit.\n#include \"edf2017_funcs.44.h\"\n#include \"native_graphics/native_cache_flush.h\"\nnamespace { struct UnlockStackWriter { uint8_t* base; void StoreWord(uint32_t address,uint32_t value) const { REX_STORE_U32(address,value); } }; }\n")
foreach(item "44:82134640:79c1ce384f56baafc0351e9a4f4e4804fd0a06b819977286680b84a2475fb2e0"
             "71:821349B8:e3eb505d40f580cbe7a4a19bc8698c34b9ac9b34b185ecd5ba0c2c9612e9a7ff"
             "16:82134AD8:a1fb6245c78642b4bdc9aaeb2554b6a9a743d6d1adc6194c8f8cf2eec9115f0b")
    string(REPLACE ":" ";" parts "${item}")
    list(GET parts 0 shard)
    list(GET parts 1 address)
    list(GET parts 2 expected)
    file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.${shard}.cpp" source)
    string(REPLACE "\r\n" "\n" source "${source}")
    string(FIND "${source}" "DEFINE_REX_FUNC(sub_${address}) {" begin)
    if(begin LESS 0)
        message(FATAL_ERROR "Missing unlock routine ${address}")
    endif()
    string(SUBSTRING "${source}" ${begin} -1 tail)
    string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
    if(end LESS 0)
        message(FATAL_ERROR "Missing unlock boundary ${address}")
    endif()
    string(SUBSTRING "${tail}" 0 ${end} body)
    string(SHA256 fingerprint "${body}")
    if(NOT fingerprint STREQUAL expected)
        message(FATAL_ERROR "${address} changed; re-audit native unlock chain")
    endif()
    string(REPLACE "DEFINE_REX_FUNC(sub_${address})" "DEFINE_REX_FUNC(edf_native_unlock_${address})" body "${body}")
    string(REPLACE "sub_82134640(ctx, base);" "__imp__edf_native_unlock_82134640(ctx, base);" body "${body}")
    string(REPLACE "sub_82141AB8(ctx, base);" "edf::native::NativeCacheFlushCpu(ctx, UnlockStackWriter{base});" body "${body}")
    string(APPEND result "\n${body}\n")
endforeach()
file(WRITE "${OUTPUT}" "${result}")
