# Preserve the audited presentation wrapper's CPU contract while removing the
# SDK's PM4_XE_SWAP emission. Native frame publication owns the actual image.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.26.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_82151460) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing presentation wrapper")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing presentation boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "3e00c92e5c922f695d3d26238724119958bcc9b53de0047532a3f7b4f844f9f6")
    message(FATAL_ERROR "51460 changed; re-audit presentation CPU effects")
endif()
file(WRITE "${OUTPUT}" "// Generated native presentation CPU tail.\n#include \"edf2017_funcs.26.h\"\n")
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.15.cpp" edram_source)
string(REPLACE "\r\n" "\n" edram_source "${edram_source}")
string(FIND "${edram_source}" "DEFINE_REX_FUNC(sub_82151080) {" edram_begin)
if(edram_begin LESS 0)
    message(FATAL_ERROR "Missing EDRAM maintenance wrapper")
endif()
string(SUBSTRING "${edram_source}" ${edram_begin} -1 edram_tail)
string(FIND "${edram_tail}" "\nDEFINE_REX_FUNC(" edram_end)
if(edram_end LESS 0)
    message(FATAL_ERROR "Missing EDRAM maintenance boundary")
endif()
string(SUBSTRING "${edram_tail}" 0 ${edram_end} edram_body)
string(SHA256 edram_fingerprint "${edram_body}")
if(NOT edram_fingerprint STREQUAL "222e7c52c8674975e4f93c114814fac26cdbc2a51b30b5c20443a2536ba315d8")
    message(FATAL_ERROR "51080 changed; re-audit removed EDRAM maintenance")
endif()
include("${SOURCE_DIR}/tools/extract-native-counter-reset.cmake")
if(TEST_MODE)
    # Keep real wrapper control flow with controlled SDK export fixtures.
    file(APPEND "${OUTPUT}" "void edf_test_present_mmio(uint32_t,uint32_t);\n#undef REX_MM_STORE_U32\n#define REX_MM_STORE_U32(address,value) edf_test_present_mmio(address,value)\n")
    foreach(item "58;__savegprlr_25" "6;__restgprlr_25" "17;__savegprlr_28" "25;__restgprlr_28" "68;__savegprlr_29" "28;__restgprlr_29" "24;__savegprlr_19" "34;__restgprlr_19" "28;__savegprlr_18" "42;__restgprlr_18" "75;__savegprlr_26" "13;__restgprlr_26")
        list(GET item 0 shard)
        list(GET item 1 name)
        file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.${shard}.cpp" helper_source)
        string(REPLACE "\r\n" "\n" helper_source "${helper_source}")
        string(FIND "${helper_source}" "DEFINE_REX_FUNC(${name}) {" helper_begin)
        if(helper_begin LESS 0)
            message(FATAL_ERROR "Missing presentation ABI helper ${name}")
        endif()
        string(SUBSTRING "${helper_source}" ${helper_begin} -1 helper_tail)
        string(FIND "${helper_tail}" "\nDEFINE_REX_FUNC(" helper_end)
        if(helper_end LESS 0)
            message(FATAL_ERROR "Missing presentation ABI helper boundary")
        endif()
        string(SUBSTRING "${helper_tail}" 0 ${helper_end} helper)
        file(APPEND "${OUTPUT}" "#include \"edf2017_funcs.${shard}.h\"\n${helper}\n")
    endforeach()
    include("${SOURCE_DIR}/tools/extract-native-pix-test.cmake")
    foreach(export VdGetSystemCommandBuffer VdPersistDisplay MmFreePhysicalMemory)
        file(APPEND "${OUTPUT}" "REX_EXTERN(edf_test_${export});\n#define __imp__${export} edf_test_${export}\n")
    endforeach()
    file(APPEND "${OUTPUT}" "REX_EXTERN(edf_test_swap);\n#define __imp__VdSwap edf_test_swap\n${body}\n")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_82151460)" "DEFINE_REX_FUNC(edf_native_present_cpu_tail)" body "${body}")
if(TEST_MODE)
    file(APPEND "${OUTPUT}" "REX_EXTERN(edf_test_native_profile_marker);\n")
    string(REPLACE "sub_821390B8(ctx, base);" "edf_test_native_profile_marker(ctx, base);" body "${body}")
endif()
string(REPLACE "__imp__VdSwap(ctx, base);" "// Native image already published; no emulated GPU swap packet." body "${body}")
# The sole D160 call reserves the removed 64-word swap packet. Do not flush or
# grow legacy storage for an image already owned by the native presenter.
string(REPLACE "sub_8213D160(ctx, base);"
    "// No legacy swap-command reservation." body "${body}")
string(REPLACE "\t// addi r11,r29,256\n\tctx.r11.s64 = ctx.r29.s64 + 256;\n\t// stw r11,40(r31)\n\tREX_STORE_U32(ctx.r31.u32 + 40, ctx.r11.u32);"
    "\t// No 256-byte swap-command cursor advance." body "${body}")
# The native presenter does not request Xbox system/scaler commands. Keep the
# zeroed result fields consumed below (status, optional format/scaler changes),
# without the SDK's BEEF command-buffer identifiers used only by removed VdSwap.
string(REPLACE "__imp__VdGetSystemCommandBuffer(ctx, base);"
    "for(uint32_t offset=0;offset<148;offset+=4) REX_STORE_U32(ctx.r3.u32+offset,0);\n\tREX_STORE_U32(ctx.r4.u32,0); // No system GPU command buffer." body "${body}")
# This call site supplies (device,0,0) to the EDRAM retraining wrapper.
# Native targets have no Xbox EDRAM to retrain. Do not enter its driver-global
# critical section or allocate its 2KB scratch command buffer on every frame.
# The original wrapper returns 1; preserve that return at the boundary.
string(REPLACE "sub_82151080(ctx, base);"
    "ctx.r3.u64 = 1; // Native D3D resources require no Xbox EDRAM retraining." body "${body}")
# All update-address stores except the r1 stack-frame store are GPU packets.
# Retain their cursor increments and every ordinary CPU state/stack write.
string(REGEX REPLACE "REX_STORE_U32\\(ea, ctx.r(10|9|8|7|6|5|4|3|30)\\.u32\\);"
    "// No native presentation packet write." body "${body}")
string(REPLACE "REX_MM_STORE_U32(ctx.r9.u32 + 24848, ctx.r11.u32);"
    "// Host texture ownership replaces the Xbox scanout-address register." body "${body}")
# These blocks contain only removed scanout/scaler packets plus the explicit
# CPU effects below. Remove their capacity flushes and 8/40-byte reservations.
# The complete original wrapper fingerprint above guards the audited boundaries.
foreach(block "82151824;821518AC" "821518AC;82151928")
    list(GET block 0 first)
    list(GET block 1 last)
    string(FIND "${body}" "\nloc_${first}:" block_begin)
    string(FIND "${body}" "\nloc_${last}:" block_end)
    if(block_begin LESS 0 OR block_end LESS block_begin)
        message(FATAL_ERROR "Native scanout/scaler block boundary changed")
    endif()
    string(SUBSTRING "${body}" 0 ${block_begin} block_head)
    string(SUBSTRING "${body}" ${block_end} -1 block_tail)
    if(first STREQUAL "82151824")
        set(cpu_effect "\tREX_STORE_U32(ctx.r31.u32 + 19980, REX_LOAD_U32(ctx.r1.u32 + 96)); // Retain cached frontbuffer address only.")
    else()
        set(cpu_effect "\tif(ctx.r29.s32 != 0) ctx.r30.s64 = 1; // Retain scaler-change bookkeeping only.")
    endif()
    set(body "${block_head}\nloc_${first}:\n${cpu_effect}\n${block_tail}")
endforeach()
string(FIND "${body}" "\nloc_82151928:" persist_begin)
string(FIND "${body}" "\nloc_821519B0:" persist_end)
if(persist_begin LESS 0 OR persist_end LESS persist_begin)
    message(FATAL_ERROR "Display persistence ownership boundary changed")
endif()
string(SUBSTRING "${body}" 0 ${persist_begin} persist_head)
string(SUBSTRING "${body}" ${persist_end} -1 persist_tail)
# NativePresentationFrames already owns the image. VdPersistDisplay's SDK
# placeholder allocation is immediately freed here and has no image content.
# Preserve the flag acknowledgement, not a fabricated allocation or return.
set(body "${persist_head}\nloc_82151928:\n\tREX_STORE_U8(ctx.r31.u32 + 10809, REX_LOAD_U8(ctx.r31.u32 + 10809) & 0xef);\n${persist_tail}")
foreach(item "66;821377E8;259534f3abd2c3cf5dd9a23c87284b63cbf0f52fa48e0ef80a0a054831cb4c7b"
             "7;82142328;e7393ab98f0163be7ae44ba6ea384cca3751712cc451ddc0433ec3c67564a12e"
             "41;82134BD8;a462f733037112635b9631807d89855a8996c55336ab222f631b4b6d4ba99a99"
             "69;8214F1D8;e651c7704e7ff7b9f7022bd2c00d67a1357fc7443c59a216842bc5c759b6cadf"
             "32;82151050;bd3f1acd3946c36bb644c438b798db4398aea81e78b3154c5efd84da9cdb6a0a"
             "40;8214F300;71f1388c046632428834a421ee2683829377ae9e5279f7dd7951725a43d05027"
             "2;82150FD0;19465a73080205c2cb67ed1cbcd4059696cfc931854ced9fc4ad4eab86d1ad20"
             "56;8214F378;c706d465fa1169c77ea6e37ca1f94180e191c4eca3c03deea82aae4bc275f878"
             "39;8213C928;8aec1fc83087bfc35c91b3b147c1369eaf076142032e1e56481b2b477b9deaff"
             "21;8213BC48;4e2ee0e1529a9a086ccb849c39787a4f827f12c2161ae28fc10c2daaf499efe6"
             "51;8213BCE0;5c54b6d1a3b32b778e950ef150328cf14c39cacdc857131ebca67e0c2a8862bd"
             "65;821390B8;219522554c0d2f6e809638435898a24ff37acb7f7f44d0e6595ee8d3856774ac"
             "8;82138158;534d8ec691ece73b06d547f1e0d277c02ca428bf4c66db19e966f8bd0bd7cc2a"
             "69;821EA3E0;0d5d6a116cd419b4f9cddb51c9481b31a94ca4aec7dc757f5c36262bf863ff78")
    list(GET item 0 shard)
    list(GET item 1 address)
    list(GET item 2 expected_hash)
    file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.${shard}.cpp" reset_source)
    string(REPLACE "\r\n" "\n" reset_source "${reset_source}")
    string(FIND "${reset_source}" "DEFINE_REX_FUNC(sub_${address}) {" reset_begin)
    if(reset_begin LESS 0)
        message(FATAL_ERROR "Missing presentation reset helper")
    endif()
    string(SUBSTRING "${reset_source}" ${reset_begin} -1 reset_tail)
    string(FIND "${reset_tail}" "\nDEFINE_REX_FUNC(" reset_end)
    if(reset_end LESS 0)
        message(FATAL_ERROR "Missing presentation reset boundary")
    endif()
    string(SUBSTRING "${reset_tail}" 0 ${reset_end} reset_body)
    string(SHA256 reset_hash "${reset_body}")
    if(NOT reset_hash STREQUAL expected_hash)
        message(FATAL_ERROR "${address} changed; re-audit native presentation reset")
    endif()
    if(TEST_MODE)
        if(address STREQUAL "8213BC48" OR address STREQUAL "8213BCE0")
            string(REPLACE "DEFINE_REX_FUNC(sub_${address})" "DEFINE_REX_FUNC(edf_test_original_${address})" reset_body "${reset_body}")
        endif()
        if(address STREQUAL "821390B8")
            file(APPEND "${OUTPUT}" "REX_EXTERN(edf_test_profile_marker_seen);\n")
            string(REPLACE "DEFINE_REX_FUNC(sub_821390B8) {" "DEFINE_REX_FUNC(sub_821390B8) {\n\tedf_test_profile_marker_seen(ctx,base);" reset_body "${reset_body}")
        endif()
        if(address STREQUAL "8213C928")
            string(REPLACE "DEFINE_REX_FUNC(sub_8213C928)" "DEFINE_REX_FUNC(edf_test_original_fence_wait)" reset_body "${reset_body}")
        endif()
        if(address STREQUAL "82138158")
            string(REPLACE "DEFINE_REX_FUNC(sub_82138158)" "DEFINE_REX_FUNC(edf_test_original_profile_result)" reset_body "${reset_body}")
        endif()
        if(address STREQUAL "8214F1D8")
            string(REPLACE "__imp__VdQueryVideoFlags" "edf_test_video_flags" reset_body "${reset_body}")
            file(APPEND "${OUTPUT}" "REX_EXTERN(edf_test_video_flags);\n")
        endif()
        if(address STREQUAL "8214F378")
            string(REPLACE "__imp__VdCallGraphicsNotificationRoutines" "edf_test_scaler_notification" reset_body "${reset_body}")
            file(APPEND "${OUTPUT}" "REX_EXTERN(edf_test_scaler_notification);\n")
        endif()
        file(APPEND "${OUTPUT}" "#include \"edf2017_funcs.${shard}.h\"\n${reset_body}\n")
    endif()
endforeach()
# Presentation supplies r4=0. 42328 only rewrites the same existing mode bits
# at this call site; 34BD8 emits GPU scissor/tile state only. Native draws bind
# host viewport/scissor themselves. Preserve the CPU dirty masks, not packets.
file(APPEND "${OUTPUT}" "DEFINE_REX_FUNC(edf_native_present_reset) {\n\tREX_FUNC_PROLOGUE();\n\tfor(uint32_t offset=0;offset<40;offset+=8) REX_STORE_U64(ctx.r3.u32+offset,~uint64_t(0));\n}\n")
file(APPEND "${OUTPUT}" "DEFINE_REX_FUNC(edf_native_scaler_config) {\n\tREX_FUNC_PROLOGUE();\n\tuint32_t words[14]{};\n\tfor(uint32_t i=0;i<6;++i) words[i]=REX_LOAD_U32(ctx.r4.u32+i*4);\n\twords[6]=words[10]=REX_LOAD_U32(ctx.r4.u32+24)?3:0;\n\tfor(uint32_t i=0;i<14;++i) REX_STORE_U32(ctx.r3.u32+13348+i*4,words[i]);\n\tREX_STORE_U8(ctx.r3.u32+10810,REX_LOAD_U8(ctx.r3.u32+10810)|0x10);\n\tctx.r3.u64=0; // No Xbox graphics-notification export.\n}\n")
string(REPLACE "sub_82151050(ctx, base);" "edf_native_scaler_config(ctx, base);" body "${body}")
string(REPLACE "sub_821377E8(ctx, base);" "edf_native_present_reset(ctx, base);" body "${body}")
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.10.cpp" scaler_source)
string(REPLACE "\r\n" "\n" scaler_source "${scaler_source}")
string(FIND "${scaler_source}" "DEFINE_REX_FUNC(sub_82150D60) {" scaler_begin)
if(scaler_begin LESS 0)
    message(FATAL_ERROR "Missing scaler helper")
endif()
string(SUBSTRING "${scaler_source}" ${scaler_begin} -1 scaler_tail)
string(FIND "${scaler_tail}" "\nDEFINE_REX_FUNC(" scaler_end)
if(scaler_end LESS 0)
    message(FATAL_ERROR "Missing scaler helper boundary")
endif()
string(SUBSTRING "${scaler_tail}" 0 ${scaler_end} scaler_body)
string(SHA256 scaler_hash "${scaler_body}")
if(NOT scaler_hash STREQUAL "99a371d6a6f00e52f1fdbbbc26d4509cd14ac2ceeed0defda56b62508125bde7")
    message(FATAL_ERROR "50D60 changed; re-audit scaler CPU prefix")
endif()
file(APPEND "${OUTPUT}" "#include \"edf2017_funcs.10.h\"\n")
if(TEST_MODE)
    string(REPLACE "DEFINE_REX_FUNC(sub_82150D60)" "DEFINE_REX_FUNC(edf_test_original_scaler)" scaler_original "${scaler_body}")
    string(REPLACE "__imp__RtlFillMemoryUlong" "edf_test_fill_scaler" scaler_original "${scaler_original}")
    string(REPLACE "__imp__VdInitializeScalerCommandBuffer" "edf_test_initialize_scaler" scaler_original "${scaler_original}")
    file(APPEND "${OUTPUT}" "REX_EXTERN(edf_test_fill_scaler);\nREX_EXTERN(edf_test_initialize_scaler);\n${scaler_original}\n")
endif()
string(FIND "${scaler_body}" "\t// lis r5,-32768" scaler_packets)
string(FIND "${scaler_body}" "\t// addi r1,r1,2528" scaler_epilogue)
if(scaler_packets LESS 0 OR scaler_epilogue LESS scaler_packets)
    message(FATAL_ERROR "Scaler packet boundary changed")
endif()
string(SUBSTRING "${scaler_body}" 0 ${scaler_packets} scaler_prefix)
string(SUBSTRING "${scaler_body}" ${scaler_epilogue} -1 scaler_suffix)
string(REPLACE "DEFINE_REX_FUNC(sub_82150D60)" "DEFINE_REX_FUNC(edf_native_scaler_cpu_tail)" scaler_prefix "${scaler_prefix}")
file(APPEND "${OUTPUT}" "${scaler_prefix}\t// Native presenter owns scaling; retain parameter helper effects, not Xbox commands.\n${scaler_suffix}\n")
if(TEST_MODE)
    # Whole-wrapper fixtures retain their controlled scaler boundary; the
    # separate paired scaler fixture below exercises the actual CPU prefix.
    file(APPEND "${OUTPUT}" "REX_EXTERN(edf_test_native_scaler_call);\n")
    string(REPLACE "sub_82150D60(ctx, base);" "edf_test_native_scaler_call(ctx, base);" body "${body}")
else()
    string(REPLACE "sub_82150D60(ctx, base);" "edf_native_scaler_cpu_tail(ctx, base);" body "${body}")
endif()
file(APPEND "${OUTPUT}" "${body}\n")
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.27.cpp" color_source)
string(REPLACE "\r\n" "\n" color_source "${color_source}")
string(FIND "${color_source}" "DEFINE_REX_FUNC(sub_82151168) {" color_begin)
if(color_begin LESS 0)
    message(FATAL_ERROR "Missing display-format helper")
endif()
string(SUBSTRING "${color_source}" ${color_begin} -1 color_tail)
string(FIND "${color_tail}" "\nDEFINE_REX_FUNC(" color_end)
if(color_end LESS 0)
    message(FATAL_ERROR "Missing display-format boundary")
endif()
string(SUBSTRING "${color_tail}" 0 ${color_end} color_body)
string(SHA256 color_fingerprint "${color_body}")
if(NOT color_fingerprint STREQUAL "e61bc0b94ca9a989ee0b77386e3209925336be5c5e4bc44410ca4f08af542ce5")
    message(FATAL_ERROR "51168 changed; re-audit display-format CPU effects")
endif()
file(APPEND "${OUTPUT}" "#include \"edf2017_funcs.27.h\"\n")
if(TEST_MODE)
    string(REPLACE "DEFINE_REX_FUNC(sub_82151168)" "DEFINE_REX_FUNC(edf_test_original_color_tail)" original_color "${color_body}")
    file(APPEND "${OUTPUT}" "${original_color}\n")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_82151168)" "DEFINE_REX_FUNC(edf_native_color_cpu_tail)" color_body "${color_body}")
# Drop the whole six-word GPU format preamble, including capacity check/flush
# and dummy cursor arithmetic. CPU default-ramp generation and capture remain.
string(FIND "${color_body}" "\t// lwz r11,48(r29)" preamble_begin)
string(FIND "${color_body}" "\t// cmplwi cr6,r28,0" preamble_end)
if(preamble_begin LESS 0 OR preamble_end LESS preamble_begin)
    message(FATAL_ERROR "Display-format preamble boundary changed")
endif()
string(SUBSTRING "${color_body}" 0 ${preamble_begin} color_head)
string(SUBSTRING "${color_body}" ${preamble_end} -1 color_rest)
set(color_body "${color_head}\tctx.r31.u64 = 0x28280136; // PWL format discriminator, not a GPU packet.\n${color_rest}")
string(REPLACE "REX_STORE_U32(ctx.r29.u32 + 40, ctx.r3.u32);"
    "// No legacy display-format reservation." color_body "${color_body}")
file(APPEND "${OUTPUT}" "${color_body}\n")
foreach(item "45;82142050;table;044d37e295da3f21b8aa123ea2d3fa38e754f7dab41d2aad93f01479f52ffbdc"
             "71;82142130;pwl;c97de6ff5a51801574f6f6381f7e5e9d9184f467b87e59ae2d3e2bfd7fe99007")
    list(GET item 0 shard)
    list(GET item 1 address)
    list(GET item 2 mode)
    list(GET item 3 expected)
    file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.${shard}.cpp" gamma_source)
    string(REPLACE "\r\n" "\n" gamma_source "${gamma_source}")
    string(FIND "${gamma_source}" "DEFINE_REX_FUNC(sub_${address}) {" gamma_begin)
    if(gamma_begin LESS 0)
        message(FATAL_ERROR "Missing gamma upload ${address}")
    endif()
    string(SUBSTRING "${gamma_source}" ${gamma_begin} -1 gamma_tail)
    string(FIND "${gamma_tail}" "\nDEFINE_REX_FUNC(" gamma_end)
    if(gamma_end LESS 0)
        message(FATAL_ERROR "Missing gamma upload boundary")
    endif()
    string(SUBSTRING "${gamma_tail}" 0 ${gamma_end} gamma_body)
    string(SHA256 gamma_hash "${gamma_body}")
    if(NOT gamma_hash STREQUAL expected)
        message(FATAL_ERROR "${address} changed; re-audit gamma CPU effects")
    endif()
    file(APPEND "${OUTPUT}" "#include \"edf2017_funcs.${shard}.h\"\n")
    if(TEST_MODE)
        string(REPLACE "DEFINE_REX_FUNC(sub_${address})" "DEFINE_REX_FUNC(edf_test_original_gamma_${mode})" original_gamma "${gamma_body}")
        file(APPEND "${OUTPUT}" "${original_gamma}\n")
    endif()
    # After the native hook snapshots the table there is no remaining CPU work
    # here. D160 only reserves space for the removed upload (and may flush or
    # grow that command buffer). Do not allocate or advance a dummy reservation.
    # Retain the observed return register, even though audited callers ignore it.
    if(mode STREQUAL "table")
        set(gamma_return 6434)
    else()
        set(gamma_return -1)
    endif()
    file(APPEND "${OUTPUT}" "DEFINE_REX_FUNC(edf_native_gamma_${mode}_cpu_tail) {\n\tREX_FUNC_PROLOGUE();\n\tctx.r3.s64 = ${gamma_return}; // Table already owned by native presentation.\n}\n")
endforeach()
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.54.cpp" wait_source)
string(REPLACE "\r\n" "\n" wait_source "${wait_source}")
string(FIND "${wait_source}" "DEFINE_REX_FUNC(sub_821512D8) {" wait_begin)
if(wait_begin LESS 0)
    message(FATAL_ERROR "Missing swap wait")
endif()
string(SUBSTRING "${wait_source}" ${wait_begin} -1 wait_tail)
string(FIND "${wait_tail}" "\nDEFINE_REX_FUNC(" wait_end)
if(wait_end LESS 0)
    message(FATAL_ERROR "Missing swap wait boundary")
endif()
string(SUBSTRING "${wait_tail}" 0 ${wait_end} wait_body)
string(SHA256 wait_hash "${wait_body}")
if(NOT wait_hash STREQUAL "5bcbf4d8a82b7d54cf1d842a1415d0f4c276b0edc3ebedcf27583fce8daf035c")
    message(FATAL_ERROR "512D8 changed; re-audit native swap wait")
endif()
file(APPEND "${OUTPUT}" "#include \"edf2017_funcs.54.h\"\nREX_EXTERN(edf_native_swap_wait);\n")
if(TEST_MODE)
    string(REPLACE "DEFINE_REX_FUNC(sub_821512D8)" "DEFINE_REX_FUNC(edf_test_original_swap_wait)" original_wait "${wait_body}")
    file(APPEND "${OUTPUT}" "${original_wait}\n")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_821512D8)" "DEFINE_REX_FUNC(edf_native_swap_wait_cpu_tail)" wait_body "${wait_body}")
string(FIND "${wait_body}" "\t// lwz r10,48(r31)" packet_begin)
string(FIND "${wait_body}" "\t// bl 0x82139148\n\tctx.lr = 0x8215144C;" packet_end)
if(packet_begin LESS 0 OR packet_end LESS packet_begin)
    message(FATAL_ERROR "Swap wait packet boundary changed")
endif()
string(SUBSTRING "${wait_body}" 0 ${packet_begin} wait_head)
string(SUBSTRING "${wait_body}" ${packet_end} -1 wait_rest)
file(APPEND "${OUTPUT}" "${wait_head}\tctx.r3.u64 = ctx.r31.u64;\n\tedf_native_swap_wait(ctx, base);\n\tctx.r3.u64 = ctx.r31.u64;\n\tctx.r4.u64 = 0;\n${wait_rest}\n")
if(TEST_MODE)
    file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.58.cpp" callback_source)
    string(REPLACE "\r\n" "\n" callback_source "${callback_source}")
    string(FIND "${callback_source}" "DEFINE_REX_FUNC(sub_82151248) {" callback_begin)
    if(callback_begin LESS 0)
        message(FATAL_ERROR "Missing swap callback")
    endif()
    string(SUBSTRING "${callback_source}" ${callback_begin} -1 callback_tail)
    string(FIND "${callback_tail}" "\nDEFINE_REX_FUNC(" callback_end)
    if(callback_end LESS 0)
        message(FATAL_ERROR "Missing swap callback boundary")
    endif()
    string(SUBSTRING "${callback_tail}" 0 ${callback_end} callback_body)
    string(SHA256 callback_hash "${callback_body}")
    if(NOT callback_hash STREQUAL "d9da0247f0d98989ac19abe1ad9773cc49790fd0985ea8d6703998b80ef0b76e")
        message(FATAL_ERROR "51248 changed; re-audit native swap pacing model")
    endif()
    string(REPLACE "DEFINE_REX_FUNC(sub_82151248)" "DEFINE_REX_FUNC(edf_test_original_swap_callback)" callback_body "${callback_body}")
    file(APPEND "${OUTPUT}" "uint32_t edf_test_swap_mmio_read(uint32_t);\n#undef REX_MM_LOAD_U32\n#define REX_MM_LOAD_U32(address) edf_test_swap_mmio_read(address)\n${callback_body}\n")
endif()
