# Preserve immediate CPU state and wrapper ABI without guest vertex storage.
function(read_draw shard name expected output)
    file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.${shard}.cpp" source)
    string(REPLACE "\r\n" "\n" source "${source}")
    string(FIND "${source}" "DEFINE_REX_FUNC(${name}) {" begin)
    if(begin LESS 0)
        message(FATAL_ERROR "Missing immediate routine ${name}")
    endif()
    string(SUBSTRING "${source}" ${begin} -1 tail)
    string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
    if(end LESS 0)
        message(FATAL_ERROR "Missing immediate routine end ${name}")
    endif()
    string(SUBSTRING "${tail}" 0 ${end} body)
    string(SHA256 fingerprint "${body}")
    if(NOT fingerprint STREQUAL expected)
        message(FATAL_ERROR "${name} changed; re-audit immediate CPU/packet separation")
    endif()
    set(${output} "${body}" PARENT_SCOPE)
endfunction()
read_draw(42 sub_821FD428 f4d458ef4d979d48cd1bcdbce8b690de6edb95f05e1fb28544b615b84b2891f7 prepare)
read_draw(10 sub_821FD8F8 e3baa6aab172748ef714fe38f10b89694a70c75dc44d7e35922149d134c8b7b2 wrapper)
string(FIND "${prepare}" "\nloc_821FD6B8:" boundary)
string(FIND "${prepare}" "\nloc_821FD8CC:" epilogue)
if(boundary LESS 0 OR epilogue LESS boundary)
    message(FATAL_ERROR "Immediate CPU/packet boundary changed")
endif()
string(SUBSTRING "${prepare}" 0 ${boundary} prefix)
string(SUBSTRING "${prepare}" ${epilogue} -1 suffix)
string(REPLACE "DEFINE_REX_FUNC(sub_821FD428)" "DEFINE_REX_FUNC(edf_native_immediate_prepare_cpu_tail)" prefix "${prefix}")
include("${CMAKE_CURRENT_LIST_DIR}/native-draw-prefix.cmake")
native_draw_packet_free("${prefix}" prefix)
# Restore the temporary stride exactly as the original does at FD6C0. No
# allocation was attempted: leave failure flags and GPU scratch unchanged.
set(finish "\nloc_821FD6B8:\n\tREX_STORE_U8(ctx.r31.u32 + 12256, ctx.r25.u8);\n\tctx.r3.u64 = 0;\n")
string(FIND "${wrapper}" "\t// cmplwi r3,0" copy_begin)
string(FIND "${wrapper}" "\nloc_821FD94C:" wrapper_end)
if(copy_begin LESS 0 OR wrapper_end LESS copy_begin)
    message(FATAL_ERROR "Immediate wrapper copy boundary changed")
endif()
# Prepare always returns no guest storage. Retain the original wrapper prologue,
# call ABI and epilogue, but no unreachable copy/cursor-commit/packet-flush calls.
string(SUBSTRING "${wrapper}" 0 ${copy_begin} wrapper_prefix)
string(SUBSTRING "${wrapper}" ${wrapper_end} -1 wrapper_suffix)
set(wrapper "${wrapper_prefix}${wrapper_suffix}")
string(REPLACE "DEFINE_REX_FUNC(sub_821FD8F8)" "DEFINE_REX_FUNC(edf_native_immediate_cpu_tail)" wrapper "${wrapper}")
string(REPLACE "sub_821FD428(ctx, base);" "__imp__edf_native_immediate_prepare_cpu_tail(ctx, base);" wrapper "${wrapper}")
file(WRITE "${OUTPUT}" "// Generated native immediate CPU tail. Do not edit.\n#include \"edf2017_funcs.42.h\"\n#include \"edf2017_funcs.10.h\"\nREX_EXTERN(__imp__edf_native_main_state_cpu_tail);\nREX_EXTERN(__imp__edf_native_immediate_prepare_cpu_tail);\n${prefix}${finish}${suffix}\n${wrapper}\n")
