# Preserve retail CPU-state operations, omitting audited packet helpers and the
# GPU draw loop. Fail closed if the complete generated routine changes.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.48.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_821FE358) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing indexed draw routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 body)
string(FIND "${body}" "\nloc_821FE5B0:" boundary)
string(FIND "${body}" "\nloc_821FE7C4:" epilogue)
string(FIND "${body}" "\nDEFINE_REX_FUNC(" end)
if(boundary LESS 0 OR epilogue LESS boundary OR end LESS epilogue)
    message(FATAL_ERROR "Indexed draw CPU/packet boundary changed")
endif()
string(SUBSTRING "${body}" 0 ${end} audited_body)
string(SHA256 fingerprint "${audited_body}")
if(NOT fingerprint STREQUAL "2bb63e149d8e10c5659a550c8b2e8b04903b429692aa331a71d766a2bc939e22")
    message(FATAL_ERROR "FE358 changed; re-audit indexed CPU/packet separation")
endif()
string(SUBSTRING "${body}" 0 ${boundary} prefix)
math(EXPR length "${end}-${epilogue}")
string(SUBSTRING "${body}" ${epilogue} ${length} suffix)
string(REPLACE "DEFINE_REX_FUNC(sub_821FE358)" "DEFINE_REX_FUNC(edf_native_indexed_cpu_tail)" prefix "${prefix}")
string(REPLACE "loc_821FE7C4:" "loc_821FE5B0:" suffix "${suffix}")
include("${CMAKE_CURRENT_LIST_DIR}/native-draw-prefix.cmake")
native_draw_packet_free("${prefix}" prefix)
file(WRITE "${OUTPUT}" "// Generated native indexed CPU tail. Do not edit.\n#include \"edf2017_funcs.48.h\"\nREX_EXTERN(__imp__edf_native_main_state_cpu_tail);\n${prefix}${suffix}\n")
