# C5F0 consumes an atomic CPU dirty range as well as constructing GPU packets.
# Preserve the actual BE68 exchange, but return zero packet words to CF60.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.4.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213C5F0) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing cache-range routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing cache-range boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "d5b2912e3b1720b06c39d1ea801ecbf63cf25714ce1a8c7faffee62b68cfe77c")
    message(FATAL_ERROR "C5F0 changed; re-audit cache-range CPU effects")
endif()
string(FIND "${body}" "loc_8213C64C:" packet_begin)
string(FIND "${body}" "\t// addi r5,r1,80" exchange_begin)
string(FIND "${body}" "\t// lwz r11,80(r1)" exchange_end)
string(FIND "${body}" "loc_8213C780:" packet_end)
if(packet_begin LESS 0 OR exchange_begin LESS packet_begin OR exchange_end LESS exchange_begin OR packet_end LESS exchange_end)
    message(FATAL_ERROR "Cache-range packet boundaries changed")
endif()
string(SUBSTRING "${body}" 0 ${packet_begin} prefix)
math(EXPR exchange_length "${exchange_end}-${exchange_begin}")
string(SUBSTRING "${body}" ${exchange_begin} ${exchange_length} exchange)
string(SUBSTRING "${body}" ${packet_end} -1 suffix)
# ECD8 also uses the address output as fallback CPU storage. Keep its allocator
# and failure behavior, but remove the cache-command words written to that space.
string(FIND "${body}" "\t// lis r10,1" reserve_end)
string(FIND "${body}" "loc_8213C764:" address_begin)
if(reserve_end LESS packet_begin OR address_begin LESS exchange_end)
    message(FATAL_ERROR "Cache reservation/address boundaries changed")
endif()
string(SUBSTRING "${body}" 0 ${reserve_end} reserve_prefix)
string(SUBSTRING "${body}" ${address_begin} -1 reserve_suffix)
string(REPLACE "DEFINE_REX_FUNC(sub_8213C5F0)" "DEFINE_REX_FUNC(edf_native_cache_reservation_cpu_tail)" reserve_prefix "${reserve_prefix}")
string(REPLACE "REX_STORE_U32(ctx.r20.u32 + 0, ctx.r21.u32);" "REX_STORE_U32(ctx.r20.u32 + 0, 0);" reserve_suffix "${reserve_suffix}")
set(reserve_body "${reserve_prefix}\tif(ctx.r24.u32) {\n${exchange}\t}\n${reserve_suffix}")
string(REPLACE "DEFINE_REX_FUNC(sub_8213C5F0)" "DEFINE_REX_FUNC(edf_native_cache_range_cpu_tail)" prefix "${prefix}")
set(cpu "loc_8213C64C:\n\tif(ctx.r24.u32) {\n${exchange}\t}\n\tREX_STORE_U32(ctx.r20.u32, 0);\n")
file(WRITE "${OUTPUT}" "// Generated native cache-range CPU tails. Do not edit.\n#include \"edf2017_funcs.4.h\"\n${prefix}${cpu}${suffix}\n${reserve_body}\n")
