# Execute the retail CPU worker unchanged, adding evidence before a null job.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.14.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8214E8E0) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing CPU worker")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing CPU worker boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "4f866c4c2947d1751b25dd7a7ace5245c9d368e513035b29ede8b39dc2f2db12")
    message(FATAL_ERROR "E8E0 changed; re-audit CPU worker instrumentation")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_8214E8E0)" "DEFINE_REX_FUNC(edf_native_worker_audit)" body "${body}")
string(REPLACE "loc_8214E98C:" "loc_8214E98C:\n\tedf_native_audit_worker_command(ctx,base,ctx.r31.u32,ctx.r3.u32);" body "${body}")
string(REPLACE "\tREX_CALL_INDIRECT_FUNC(ctx.ctr.u32);" "\tif(!ctx.ctr.u32) edf_native_null_worker_job(ctx,base);\n\tREX_CALL_INDIRECT_FUNC(ctx.ctr.u32);" body "${body}")
file(WRITE "${OUTPUT}" "// Generated retail CPU worker with null-job diagnostics. Do not edit.\n#include \"edf2017_funcs.14.h\"\nREX_EXTERN(edf_native_null_worker_job);\nvoid edf_native_audit_worker_command(PPCContext&,uint8_t*,uint32_t,uint32_t);\n${body}\n")
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.73.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8214E640) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing CPU command traversal")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing CPU command traversal boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "2bd0cadb2fd34840d05d0b5ba86b940368907dbb303fb3c4c278428dd6aaabfe")
    message(FATAL_ERROR "E640 changed; re-audit CPU traversal instrumentation")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_8214E640)" "DEFINE_REX_FUNC(edf_native_worker_commands_audit)" body "${body}")
string(REPLACE "\t// lwz r10,0(r31)" "\tedf_native_audit_worker_command(ctx,base,ctx.r30.u32,ctx.r31.u32);\n\t// lwz r10,0(r31)" body "${body}")
file(APPEND "${OUTPUT}" "#include \"edf2017_funcs.73.h\"\n${body}\n")
