# Build a test fixture from the actual generated routines, not a hand-written
# imitation. Generated game code stays in the build directory.
set(result "// Generated native-tail test fixture. Do not edit.\n")
string(APPEND result "#include \"native_graphics/native_scene_execution.h\"\nnamespace edf::native { void EnterNativeSceneBoundary(NativeSceneBoundary); }\n")
# The extracted hooks time themselves under edf_native_load_trace; off here.
string(APPEND result "#include \"native_graphics/native_load_trace.h\"\nstatic bool LoadTraceOn() { return false; }\n")
set(enclosing_items "66:sub_8214ECD8" "74:sub_82134408" "46:sub_821E8740")
list(APPEND enclosing_items "32:sub_8213AD70")
list(APPEND enclosing_items "25:sub_821EA320")
list(APPEND enclosing_items "16:sub_821E9BA0")
list(APPEND enclosing_items "49:sub_8213BDF8")
list(APPEND enclosing_items "71:sub_821349B8" "44:sub_82134640")
list(APPEND enclosing_items "16:sub_82134AD8")
list(APPEND enclosing_items "24:sub_82134958" "76:sub_82134A78")
list(APPEND enclosing_items "32:sub_8212FC28")
list(APPEND enclosing_items "41:sub_8212F4B8")
list(APPEND enclosing_items "40:sub_82149A90" "60:sub_8214B0A0")
list(APPEND enclosing_items "80:sub_82137410" "31:sub_821375C0")
list(APPEND enclosing_items "38:sub_821B8E48" "31:sub_82149248" "53:sub_82149358")
list(APPEND enclosing_items "60:sub_821D9600")
list(APPEND enclosing_items "50:sub_821498C8" "35:sub_82149608")
list(APPEND enclosing_items "33:sub_82147BA0" "63:sub_82149AB0")
list(APPEND enclosing_items "5:sub_821BC588" "70:sub_821BC430")
list(APPEND enclosing_items "51:sub_8214EE50")
list(APPEND enclosing_items "19:sub_8214EFF8")
list(APPEND enclosing_items "48:sub_82135418")
set(ring_items "33:sub_8213C410" "3:__savegprlr_21" "68:__restgprlr_21")
list(APPEND ring_items "29:sub_8214EBA0" "58:sub_82151248")
list(APPEND ring_items "31:sub_8213BD90")
list(APPEND ring_items "19:sub_8213C9F0" "6:__savegprlr_27" "58:__restgprlr_27")
set(reset_items "38:sub_8213D298" "7:sub_8213D1C8" "25:__savegprlr_24" "17:__restgprlr_24" "39:sub_8213C928" "68:__savegprlr_29" "28:__restgprlr_29" "62:sub_8213D0F8" "4:sub_8213C5F0" "11:sub_8213BE68" "52:sub_8213CF60")
set(output_patch_items "66:sub_8213E800" "65:sub_8213E678" "34:sub_8213E748" "50:sub_8213E950" "24:__savegprlr_19" "34:__restgprlr_19" "5:sub_82141AB8" "17:sub_8213ECB0")
set(shader_load_items "73:sub_8213EAB0" "58:__savegprlr_25" "6:__restgprlr_25" "54:sub_8213D750" "12:sub_8213E070" "32:sub_8213EB68" ${output_patch_items} ${reset_items} ${ring_items} ${enclosing_items})
foreach(item "42:sub_821FD428" "10:sub_821FD8F8" "12:__savegprlr_22" "17:__savegprlr_28" "25:__restgprlr_28" "50:__restgprlr_22" "48:sub_821FE358" "7:__savegprlr_14" "16:__restgprlr_14" "15:sub_8213DB60" "75:__savegprlr_26" "13:__restgprlr_26" "31:sub_8213DC20" "4:__savegprlr_23" "22:__restgprlr_23" "14:sub_8213D938" "20:__savegprlr_20" "72:__restgprlr_20" ${shader_load_items})
    string(REPLACE ":" ";" parts "${item}")
    list(GET parts 0 shard)
    list(GET parts 1 name)
    file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.${shard}.cpp" source)
    string(FIND "${source}" "DEFINE_REX_FUNC(${name}) {" begin)
    if(begin LESS 0)
        message(FATAL_ERROR "Missing native-tail fixture routine ${name}")
    endif()
    string(SUBSTRING "${source}" ${begin} -1 tail)
    string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
    if(end LESS 0)
        message(FATAL_ERROR "Missing fixture boundary after ${name}")
    endif()
    string(SUBSTRING "${tail}" 0 ${end} body)
    if(name STREQUAL "sub_8212F4B8")
        # Keep the retail selector and null branch; isolate only its endpoints.
        string(REPLACE "DEFINE_REX_FUNC(sub_8212F4B8)" "DEFINE_REX_FUNC(edf_test_generic_free_original)" body "${body}")
        string(REPLACE "sub_8212FC28(ctx, base)" "edf_test_generic_physical_free(ctx, base)" body "${body}")
        string(REPLACE "sub_8212FC40(ctx, base)" "edf_test_generic_cpu_free(ctx, base)" body "${body}")
        string(PREPEND body "REX_EXTERN(edf_test_generic_physical_free);\nREX_EXTERN(edf_test_generic_cpu_free);\n")
    endif()
    if(name STREQUAL "sub_8213BD90")
        string(REPLACE "DEFINE_REX_FUNC(sub_8213BD90)" "DEFINE_REX_FUNC(edf_test_ring_copy_original)" body "${body}")
    endif()
    if(name STREQUAL "sub_8213C410")
        # Intercept only the Xbox MMIO endpoint, not original CPU control flow.
        string(REPLACE "REX_MM_STORE_U32(ctx.r11.u32 + 1812, ctx.r29.u32);"
            "edf_test_ring_doorbell(ctx, base);" body "${body}")
        string(PREPEND body "REX_EXTERN(edf_test_ring_doorbell);\n")
    endif()
    if(name STREQUAL "sub_82151248")
        # Model the two timing-register reads only. Guest CPU logic stays retail.
        string(REPLACE "REX_MM_LOAD_U32(ctx.r10.u32 + 25904)"
            "edf_test_signal_mmio(ctx.r10.u32 + 25904)" body "${body}")
        string(REPLACE "REX_MM_LOAD_U32(ctx.r9.u32 + 25988)"
            "edf_test_signal_mmio(ctx.r9.u32 + 25988)" body "${body}")
        string(PREPEND body "uint32_t edf_test_signal_mmio(uint32_t address);\n")
    endif()
    string(APPEND result "#include \"edf2017_funcs.${shard}.h\"\n${body}\n")
endforeach()
# Exercise the actual native import adapter against a controlled SDK provider.
file(READ "${SOURCE_DIR}/src/native_graphics/guest_shader_bridge.cpp" bridge)
# The fixture sees the individual cvars: undo the renderer preset layer
# (EDF_NATIVE_FLAG(x) -> REXCVAR_GET(edf_native_x)) before any replacement.
string(REGEX REPLACE "EDF_NATIVE_FLAG\\(([a-z_0-9]+)\\)" "REXCVAR_GET(edf_native_\\1)" bridge "${bridge}")
string(FIND "${bridge}" "REX_HOOK_RAW(sub_82134AD8) {" inline_begin)
if(inline_begin LESS 0)
    message(FATAL_ERROR "Missing inline index unlock hook")
endif()
string(SUBSTRING "${bridge}" ${inline_begin} -1 inline_tail)
string(FIND "${inline_tail}" "\n}" inline_end)
if(inline_end LESS 0)
    message(FATAL_ERROR "Missing inline index unlock boundary")
endif()
math(EXPR inline_end "${inline_end}+2")
string(SUBSTRING "${inline_tail}" 0 ${inline_end} inline_body)
string(REPLACE "REX_HOOK_RAW(sub_82134AD8)" "DEFINE_REX_FUNC(edf_test_inline_unlock)" inline_body "${inline_body}")
string(REPLACE "REXCVAR_GET(edf_native_shader_bridge)" "edf_test_texture_native()" inline_body "${inline_body}")
string(REPLACE "__imp__sub_82134AD8" "edf_test_inline_unlock_original" inline_body "${inline_body}")
string(REPLACE "__imp__edf_native_unlock_82134AD8" "edf_test_inline_unlock_original" inline_body "${inline_body}")
string(REPLACE "NotifyCompletedNativeBufferWrite" "edf_test_inline_completed" inline_body "${inline_body}")
string(REPLACE "NotifyNativeBufferUpdate" "edf_test_inline_renderer_update" inline_body "${inline_body}")
string(APPEND result "\n#include \"native_graphics/native_buffer_writes.h\"\nedf::native::NativeBufferWrites::WriterScope BeginNativeBufferWrite(uint8_t*,uint32_t,uint32_t,bool,edf::native::NativeBufferWrites::WriterKind);\n")
string(APPEND result "\n#include \"native_graphics/native_buffer_write_frame.h\"\nbool edf_test_texture_native();\nREX_EXTERN(edf_test_inline_unlock_original);\nvoid edf_test_inline_completed(uint8_t*,uint32_t,uint32_t);\nvoid edf_test_inline_renderer_update(uint8_t*,uint32_t,bool);\n${inline_body}\n")
string(APPEND result "\n#include \"native_graphics/native_buffer_writes.h\"\nedf::native::NativeBufferWrites::WriterScope BeginNativeBufferWrite(uint8_t*,uint32_t,uint32_t,bool=false,edf::native::NativeBufferWrites::WriterKind=edf::native::NativeBufferWrites::WriterKind::Bulk);\n")
string(APPEND result "\nvoid edf_test_completed_copy(uint8_t*,uint32_t,uint32_t,bool=false,bool=false,edf::native::NativeBufferWrites::WriterSite={});\n")
foreach(name sub_821E8320 sub_821E8740 sub_8213BDF8 sub_821349B8)
    string(FIND "${bridge}" "REX_HOOK_RAW(${name}) {" begin)
    if(begin LESS 0)
        message(FATAL_ERROR "Missing native copy hook ${name}")
    endif()
    string(SUBSTRING "${bridge}" ${begin} -1 tail)
    string(FIND "${tail}" "\n}" end)
    if(end LESS 0)
        message(FATAL_ERROR "Missing native copy hook boundary ${name}")
    endif()
    math(EXPR end "${end}+2")
    string(SUBSTRING "${tail}" 0 ${end} body)
    string(REPLACE "REX_HOOK_RAW(${name})" "DEFINE_REX_FUNC(edf_test_${name})" body "${body}")
    string(REPLACE "NotifyCompletedNativeBufferWrite" "edf_test_completed_copy" body "${body}")
    if(name STREQUAL "sub_821349B8")
        string(APPEND result "\nREX_EXTERN(__imp__edf_native_unlock_821349B8);\n")
        string(REPLACE "REXCVAR_GET(edf_native_shader_bridge)" "edf_test_texture_native()" body "${body}")
        string(REPLACE "NotifyNativeBufferUpdate" "edf_test_vertex_unlock_update" body "${body}")
        string(APPEND result "\nvoid edf_test_vertex_unlock_update(uint8_t*,uint32_t,bool);\n")
    endif()
    if(name STREQUAL "sub_821E8320")
        string(REPLACE "__imp__sub_821E8320(ctx,base)" "edf_test_copy_provider(ctx,base)" body "${body}")
        string(APPEND result "\nREX_EXTERN(edf_test_copy_provider);\n")
    endif()
    string(APPEND result "\nREX_EXTERN(__imp__${name});\n${body}\n")
endforeach()
string(FIND "${bridge}" "REX_HOOK_RAW(sub_82134408) {" lock_begin)
if(lock_begin LESS 0)
    message(FATAL_ERROR "Missing native resource lock hook")
endif()
string(SUBSTRING "${bridge}" ${lock_begin} -1 lock_tail)
string(FIND "${lock_tail}" "\n}" lock_end)
if(lock_end LESS 0)
    message(FATAL_ERROR "Missing native resource lock hook boundary")
endif()
math(EXPR lock_end "${lock_end}+2")
string(SUBSTRING "${lock_tail}" 0 ${lock_end} lock_body)
string(REPLACE "REX_HOOK_RAW(sub_82134408)" "DEFINE_REX_FUNC(edf_test_native_resource_lock)" lock_body "${lock_body}")
string(REPLACE "REXCVAR_GET(edf_native_shader_bridge)" "edf_test_texture_native()" lock_body "${lock_body}")
string(APPEND result "\n#include <rex/logging.h>\nbool edf_test_texture_native();\nREX_EXTERN(__imp__sub_82134408);\nREX_EXTERN(__imp__edf_native_buffer_lock_cpu_tail);\n${lock_body}\n")
string(APPEND result "\nstruct EdfTestBindingReader { uint8_t* base; uint32_t Add(uint32_t a,uint32_t b) const { return a+b; } uint32_t Word(uint32_t a) const { return REX_LOAD_U32(a); } void StoreWord(uint32_t a,uint32_t v) const { REX_STORE_U32(a,v); } };\n")
foreach(name sub_82149A90 sub_8214B0A0 sub_821498C8 sub_82149608 sub_82147BA0 sub_82149AB0)
    string(FIND "${bridge}" "REX_HOOK_RAW(${name}) {" begin)
    if(begin LESS 0)
        message(FATAL_ERROR "Missing declaration binding hook ${name}")
    endif()
    string(SUBSTRING "${bridge}" ${begin} -1 tail)
    string(FIND "${tail}" "\n}" end)
    if(end LESS 0)
        message(FATAL_ERROR "Missing declaration binding hook boundary")
    endif()
    math(EXPR end "${end}+2")
    string(SUBSTRING "${tail}" 0 ${end} body)
    string(REPLACE "REX_HOOK_RAW(${name})" "DEFINE_REX_FUNC(edf_test_${name})" body "${body}")
    # These publication tests compare the compatibility branch with retail.
    # Native shader retirement/default semantics have their own binding suite.
    # Keep an explicit rejecting provider so accidentally selecting that branch
    # cannot silently turn this fixture into evidence for native activation.
    string(REPLACE "REXCVAR_GET(edf_native_shader_bridge)" "false" body "${body}")
    string(REPLACE "REXCVAR_GET(edf_native_material_activation)" "false" body "${body}")
    # The extracted publication fixture deliberately selects compatibility;
    # production group eligibility is tested through the shared preflight.
    string(REPLACE "(!edf::native::native_queued_scene_group || !edf::native::native_queued_scene_group->material_compatibility_only)" "true" body "${body}")
    string(REPLACE "BindNativeShaderResource" "edf_test_unexpected_native_shader_binding" body "${body}")
    string(REPLACE "edf::native::GuestReader" "EdfTestBindingReader" body "${body}")
    string(APPEND result "\nvoid edf_test_unexpected_native_shader_binding(PPCContext&,uint8_t*,bool);\n")
    string(REPLACE "PublishNativeDeclarationBinding" "edf_test_declaration_binding" body "${body}")
    string(REPLACE "PublishNativeShaderBinding" "edf_test_shader_binding" body "${body}")
    string(REPLACE "PublishNativeDeclarationContents" "edf_test_declaration_contents" body "${body}")
    string(APPEND result "\nvoid edf_test_declaration_contents(uint8_t*,uint32_t);\n")
    string(APPEND result "\nREX_EXTERN(__imp__${name});\nvoid edf_test_declaration_binding(uint32_t,uint32_t);\nvoid edf_test_shader_binding(uint32_t,uint32_t,bool);\n${body}\n")
endforeach()
string(FIND "${bridge}" "REX_HOOK_RAW(edf_native_NtReadFile) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing native file-read adapter")
endif()
string(SUBSTRING "${bridge}" ${begin} -1 tail)
string(FIND "${tail}" "\n}" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing native file-read adapter boundary")
endif()
math(EXPR end "${end}+2")
string(SUBSTRING "${tail}" 0 ${end} body)
string(REPLACE "REX_HOOK_RAW(edf_native_NtReadFile)" "DEFINE_REX_FUNC(edf_test_native_file_read)" body "${body}")
string(REPLACE "NotifyCompletedNativeBufferWrite" "edf_test_completed_file_write" body "${body}")
string(APPEND result "\nREX_EXTERN(__imp__NtReadFile);\nvoid edf_test_completed_file_write(uint8_t*,uint32_t,uint32_t,bool);\n${body}\n")
string(FIND "${bridge}" "REX_HOOK_RAW(sub_821EA320) {" move_begin)
string(FIND "${bridge}" "REX_HOOK_RAW(edf_native_RtlFillMemoryUlong) {" fill_begin)
if(fill_begin LESS 0)
    message(FATAL_ERROR "Missing native word-fill adapter")
endif()
string(SUBSTRING "${bridge}" ${fill_begin} -1 fill_tail)
string(FIND "${fill_tail}" "\n}" fill_end)
if(fill_end LESS 0)
    message(FATAL_ERROR "Missing native word-fill adapter boundary")
endif()
math(EXPR fill_end "${fill_end}+2")
string(SUBSTRING "${fill_tail}" 0 ${fill_end} fill_body)
string(REPLACE "REX_HOOK_RAW(edf_native_RtlFillMemoryUlong)" "DEFINE_REX_FUNC(edf_test_native_word_fill)" fill_body "${fill_body}")
string(REPLACE "NotifyCompletedNativeBufferWrite" "edf_test_completed_word_fill" fill_body "${fill_body}")
string(APPEND result "\nREX_EXTERN(__imp__RtlFillMemoryUlong);\nvoid edf_test_completed_word_fill(uint8_t*,uint32_t,uint32_t,bool);\n${fill_body}\n")
if(move_begin LESS 0)
    message(FATAL_ERROR "Missing native backward-copy adapter")
endif()
string(SUBSTRING "${bridge}" ${move_begin} -1 move_tail)
string(FIND "${move_tail}" "\n}" move_end)
if(move_end LESS 0)
    message(FATAL_ERROR "Missing native backward-copy adapter boundary")
endif()
math(EXPR move_end "${move_end}+2")
string(SUBSTRING "${move_tail}" 0 ${move_end} move_body)
string(REPLACE "REX_HOOK_RAW(sub_821EA320)" "DEFINE_REX_FUNC(edf_test_native_move)" move_body "${move_body}")
string(REPLACE "NotifyCompletedNativeBufferWrite" "edf_test_completed_move" move_body "${move_body}")
string(APPEND result "\nREX_EXTERN(__imp__sub_821EA320);\nvoid edf_test_completed_move(uint8_t*,uint32_t,uint32_t,bool,bool,edf::native::NativeBufferWrites::WriterSite);\n${move_body}\n")
string(FIND "${bridge}" "REX_HOOK_RAW(sub_821E9BA0) {" fill_begin)
if(fill_begin LESS 0)
    message(FATAL_ERROR "Missing native bulk-fill adapter")
endif()
string(SUBSTRING "${bridge}" ${fill_begin} -1 fill_tail)
string(FIND "${fill_tail}" "\n}" fill_end)
if(fill_end LESS 0)
    message(FATAL_ERROR "Missing native bulk-fill adapter boundary")
endif()
math(EXPR fill_end "${fill_end}+2")
string(SUBSTRING "${fill_tail}" 0 ${fill_end} fill_body)
string(REPLACE "REX_HOOK_RAW(sub_821E9BA0)" "DEFINE_REX_FUNC(edf_test_native_fill)" fill_body "${fill_body}")
string(REPLACE "NotifyCompletedNativeBufferWrite" "edf_test_completed_move" fill_body "${fill_body}")
string(APPEND result "\nREX_EXTERN(__imp__sub_821E9BA0);\n${fill_body}\n")
string(FIND "${bridge}" "REX_HOOK_RAW(sub_8212FC28) {" backing_begin)
if(backing_begin LESS 0)
    message(FATAL_ERROR "Missing native chunk free hook")
endif()
string(SUBSTRING "${bridge}" ${backing_begin} -1 backing_tail)
string(FIND "${backing_tail}" "\n}" backing_end)
if(backing_end LESS 0)
    message(FATAL_ERROR "Missing native chunk free hook boundary")
endif()
math(EXPR backing_end "${backing_end}+2")
string(SUBSTRING "${backing_tail}" 0 ${backing_end} backing_body)
string(REPLACE "REX_HOOK_RAW(sub_8212FC28)" "DEFINE_REX_FUNC(edf_test_chunk_free)" backing_body "${backing_body}")
string(REPLACE "REXCVAR_GET(edf_native_shader_bridge)" "edf_test_texture_native()" backing_body "${backing_body}")
string(REPLACE "RetireNativePoolBackings" "edf_test_retire_pool_backings" backing_body "${backing_body}")
string(APPEND result "\n#include <array>\n#include <span>\nREX_EXTERN(__imp__sub_8212FC28);\nedf::native::NativeBufferWrites::ReleaseScopes edf_test_retire_pool_backings(uint8_t*,std::span<const uint32_t>);\n${backing_body}\n")
string(FIND "${bridge}" "REX_HOOK_RAW(sub_8212F4B8) {" generic_begin)
if(generic_begin LESS 0)
    message(FATAL_ERROR "Missing native generic free hook")
endif()
string(SUBSTRING "${bridge}" ${generic_begin} -1 generic_tail)
string(FIND "${generic_tail}" "\n}" generic_end)
if(generic_end LESS 0)
    message(FATAL_ERROR "Missing native generic free hook boundary")
endif()
math(EXPR generic_end "${generic_end}+2")
string(SUBSTRING "${generic_tail}" 0 ${generic_end} generic_body)
string(REPLACE "REX_HOOK_RAW(sub_8212F4B8)" "DEFINE_REX_FUNC(edf_test_generic_free)" generic_body "${generic_body}")
string(REPLACE "__imp__sub_8212F4B8" "__imp__edf_test_generic_free_original" generic_body "${generic_body}")
string(REPLACE "REXCVAR_GET(edf_native_shader_bridge)" "edf_test_texture_native()" generic_body "${generic_body}")
string(REPLACE "RetireNativePoolBackings" "edf_test_retire_pool_backings" generic_body "${generic_body}")
string(APPEND result "\nREX_EXTERN(__imp__edf_test_generic_free_original);\n${generic_body}\n")
file(WRITE "${OUTPUT}" "${result}")
