file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.74.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_82134408) {" begin)
if(begin LESS 0)
  message(FATAL_ERROR "Missing buffer lock helper")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "b13242eda2f1530ad7e4b909c16c2f46f0b5a3b0c4256c9668faf10655ffc6df")
  message(FATAL_ERROR "Buffer lock changed; re-audit CPU/packet boundaries")
endif()
string(FIND "${body}" "loc_821344E8:" packet_begin)
string(FIND "${body}" "loc_82134570:" packet_end)
if(packet_begin LESS 0 OR packet_end LESS packet_begin)
  message(FATAL_ERROR "Buffer lock packet boundary changed")
endif()
string(SUBSTRING "${body}" 0 ${packet_begin} prefix)
string(SUBSTRING "${body}" ${packet_end} -1 suffix)
string(REPLACE "DEFINE_REX_FUNC(sub_82134408)" "DEFINE_REX_FUNC(edf_native_buffer_lock_cpu_tail)" prefix "${prefix}")
string(REPLACE "loc_82134570:" "loc_82134570:\n{\n  const uint32_t native_header=ctx.r27.u32;\n  const auto native_header_writer=edf_native_begin_lock_header_write(base,native_header);" suffix "${suffix}")
string(REPLACE "\t// mr r3,r28" "  edf_native_complete_lock_header_write(base,native_header);\n}\n\t// mr r3,r28" suffix "${suffix}")
# Preserve resource waits, off-thread atomic dirty-range accumulation, dirty
# subresource bounds, returned address/alias and atomic lock count. Only the
# render-thread cache packet reservation/encoding and cursor update disappear.
file(WRITE "${OUTPUT}" "// Generated native buffer-lock CPU tail.\n#include \"edf2017_funcs.74.h\"\n#include \"native_graphics/native_buffer_writes.h\"\nedf::native::NativeBufferWrites::WriterScope edf_native_begin_lock_header_write(uint8_t*,uint32_t);\nvoid edf_native_complete_lock_header_write(uint8_t*,uint32_t);\n${prefix}loc_821344E8:\n${suffix}\n")
foreach(item "24:82134958:47c2adb607aa5569b17cb9313efbec769da3e1dc36de01c55d55bab9bdc407ae"
             "76:82134A78:b308f15a043c629d726a0d9b78da221e48ef6886e355a67cb51fe34e7fb8e928")
  string(REPLACE ":" ";" parts "${item}")
  list(GET parts 0 shard)
  list(GET parts 1 address)
  list(GET parts 2 expected)
  file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.${shard}.cpp" source)
  string(REPLACE "\r\n" "\n" source "${source}")
  string(FIND "${source}" "DEFINE_REX_FUNC(sub_${address}) {" begin)
  if(begin LESS 0)
    message(FATAL_ERROR "Missing buffer-lock wrapper ${address}")
  endif()
  string(SUBSTRING "${source}" ${begin} -1 tail)
  string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
  if(end LESS 0)
    message(FATAL_ERROR "Missing buffer-lock wrapper boundary ${address}")
  endif()
  string(SUBSTRING "${tail}" 0 ${end} body)
  string(SHA256 fingerprint "${body}")
  if(NOT fingerprint STREQUAL expected)
    message(FATAL_ERROR "${address} changed; re-audit lock argument/ABI contract")
  endif()
  string(REPLACE "DEFINE_REX_FUNC(sub_${address})" "DEFINE_REX_FUNC(edf_native_lock_${address})" body "${body}")
  string(REPLACE "sub_82134408(ctx, base);" "__imp__edf_native_buffer_lock_cpu_tail(ctx, base);" body "${body}")
  file(APPEND "${OUTPUT}" "\n${body}\n")
endforeach()
