# EB68 retains CPU cache/fence/ID bookkeeping but has no Xbox code to patch.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.32.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213EB68) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing shader-cache routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing shader-cache boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "5b78ea4e73dfa48a29d6cd84117727d85b9d962a2974db11bfe65d2dfb9e9338")
    message(FATAL_ERROR "EB68 changed; re-audit shader-cache CPU/patch separation")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_8213EB68)" "DEFINE_REX_FUNC(edf_native_shader_cache_cpu_tail)" body "${body}")
string(REPLACE "sub_8213E070(ctx, base);" "// No Xbox shader instructions exist to patch." body "${body}")
file(WRITE "${OUTPUT}" "// Generated native shader-cache CPU tail. Do not edit.\n#include \"edf2017_funcs.32.h\"\n${body}\n")
