file(READ "${SOURCE}" source)
# Undo the renderer preset layer: EDF_NATIVE_FLAG(x) -> REXCVAR_GET(edf_native_x).
string(REGEX REPLACE "EDF_NATIVE_FLAG\\(([a-z_0-9]+)\\)" "REXCVAR_GET(edf_native_\\1)" source "${source}")
string(FIND "${source}" "void ConstructNativeModelBuffer(PPCContext& ctx,uint8_t* base,bool index) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing native model constructor")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\n}" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing native model constructor boundary")
endif()
math(EXPR end "${end}+2")
string(SUBSTRING "${tail}" 0 ${end} body)
file(WRITE "${OUTPUT}" "// Extracted production constructor; do not edit.\n${body}\n")
string(FIND "${source}" "REX_HOOK_RAW(sub_821D3748) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing native pool block release hook")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\n}" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing native pool block release boundary")
endif()
math(EXPR end "${end}+2")
string(SUBSTRING "${tail}" 0 ${end} body)
file(APPEND "${OUTPUT}" "\n// Extracted production block release hook.\n${body}\n")
