# Preserve CPU descriptor/default state; omit the trailing Xbox setup packets.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.19.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8214EFF8) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing device default-state initializer")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing device default-state boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "49494fb2e42a4e64941f414b640ca567ca54e4e8b607c80da4b23ea042497845")
    message(FATAL_ERROR "Device defaults changed; re-audit CPU/packet boundaries")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_8214EFF8)" "DEFINE_REX_FUNC(edf_native_device_defaults)" body "${body}")
string(FIND "${body}" "\t// lwz r11,40(r31)" packet_begin)
string(FIND "${body}" "\t// addi r1,r1,128" packet_end)
if(packet_begin LESS 0 OR packet_end LESS packet_begin)
    message(FATAL_ERROR "Missing device default packet tail")
endif()
string(SUBSTRING "${body}" 0 ${packet_begin} prefix)
string(SUBSTRING "${body}" ${packet_end} -1 suffix)
# 10788 is CPU state interleaved into the reservation block. Keep the original
# r10 value (14). The retail packet tail leaves r3=3650 on both branch paths.
set(body "${prefix}\tREX_STORE_U32(ctx.r31.u32 + 10788, ctx.r10.u32);\n\tctx.r3.s64 = 3650;\n${suffix}")
file(WRITE "${OUTPUT}" "// Generated native device defaults. Do not edit.\n#include \"edf2017_funcs.19.h\"\n${body}\n")
