foreach(item "6;__savegprlr_27" "58;__restgprlr_27")
  list(GET item 0 shard)
  list(GET item 1 helper)
  file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.${shard}.cpp" helper_source)
  string(FIND "${helper_source}" "DEFINE_REX_FUNC(${helper}) {" helper_begin)
  string(SUBSTRING "${helper_source}" ${helper_begin} -1 helper_tail)
  string(FIND "${helper_tail}" "\nDEFINE_REX_FUNC(" helper_end)
  string(SUBSTRING "${helper_tail}" 0 ${helper_end} helper_body)
  file(APPEND "${OUTPUT}" "\n#include \"edf2017_funcs.${shard}.h\"\n${helper_body}\n")
endforeach()
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.23.cpp" pix_source)
string(REPLACE "\r\n" "\n" pix_source "${pix_source}")
string(FIND "${pix_source}" "DEFINE_REX_FUNC(sub_82138858) {" pix_begin)
if(pix_begin LESS 0)
  message(FATAL_ERROR "Missing PIX dispatcher")
endif()
string(SUBSTRING "${pix_source}" ${pix_begin} -1 pix_tail)
string(FIND "${pix_tail}" "\nDEFINE_REX_FUNC(" pix_end)
if(pix_end LESS 0)
  message(FATAL_ERROR "Missing PIX dispatcher end")
endif()
string(SUBSTRING "${pix_tail}" 0 ${pix_end} pix_body)
string(SHA256 pix_hash "${pix_body}")
if(NOT pix_hash STREQUAL "7ee084c493d6cb01912366a4234644f3d9f212b05e7c4aa3983aee8f5fe25ddf")
  message(FATAL_ERROR "PIX dispatcher changed; re-audit monitor dispatch")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_82138858)" "DEFINE_REX_FUNC(edf_test_pix_dispatch)" pix_body "${pix_body}")
string(REPLACE "REX_CALL_INDIRECT_FUNC(ctx.ctr.u32);" "edf_test_pix_callback(ctx,base);" pix_body "${pix_body}")
string(REGEX REPLACE "sub_(82145078|821F9FD8|821387E8|8213D1C8|82144298|821FA060|82142398)\\(ctx, base\\);"
  "edf_test_pix_special_service(ctx,base);" pix_body "${pix_body}")
file(APPEND "${OUTPUT}" "\n#include \"edf2017_funcs.23.h\"\nREX_EXTERN(edf_test_pix_callback);\nREX_EXTERN(edf_test_pix_special_service);\n${pix_body}\n")
