file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.25.cpp" counter_source)
string(REPLACE "\r\n" "\n" counter_source "${counter_source}")
string(FIND "${counter_source}" "DEFINE_REX_FUNC(sub_82139228) {" counter_begin)
if(counter_begin LESS 0)
  message(FATAL_ERROR "Missing counter resetter")
endif()
string(SUBSTRING "${counter_source}" ${counter_begin} -1 counter_tail)
string(FIND "${counter_tail}" "\nDEFINE_REX_FUNC(" counter_end)
if(counter_end LESS 0)
  message(FATAL_ERROR "Missing counter resetter end boundary")
endif()
string(SUBSTRING "${counter_tail}" 0 ${counter_end} counter_body)
string(SHA256 counter_hash "${counter_body}")
if(NOT counter_hash STREQUAL "c44ff0e1a7c2634e343bf167d925530b20caa881a822a9ee2c1643a86f3ef796")
  message(FATAL_ERROR "Counter resetter changed; re-audit outputs and callback boundaries")
endif()
file(APPEND "${OUTPUT}" "\n#include \"edf2017_funcs.25.h\"\n")
if(TEST_MODE)
  string(REPLACE "REX_QUERY_TIMEBASE()" "uint64_t(0x12345678abcdef01)" counter_body "${counter_body}")
  string(REPLACE "REX_CALL_INDIRECT_FUNC(ctx.ctr.u32);" "edf_test_counter_callback(ctx,base);" counter_body "${counter_body}")
  string(REPLACE "DEFINE_REX_FUNC(sub_82139228)" "DEFINE_REX_FUNC(edf_test_counter_reset)" counter_original "${counter_body}")
  file(APPEND "${OUTPUT}" "REX_EXTERN(edf_test_counter_callback);\n${counter_original}\n")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_82139228)" "DEFINE_REX_FUNC(edf_native_counter_reset_cpu_tail)" counter_body "${counter_body}")
# Only the audited non-accounting device fields; stack stores remain unchanged.
string(REGEX REPLACE "REX_STORE_U32\\((ctx\\.r31\\.u32 \\+ (15144|15148|20076|20080|20084|20088)), (ctx\\.r[0-9]+\\.u32)\\);"
  "edf_native_counter_store_word(base, \\1, \\3);" counter_body "${counter_body}")
string(REPLACE "REX_STORE_U32(ctx.r29.u32 + 0, ctx.r3.u32);"
  "edf_native_counter_store_word(base, ctx.r29.u32, ctx.r3.u32);" counter_body "${counter_body}")
file(APPEND "${OUTPUT}" "void edf_native_counter_store_word(uint8_t*,uint32_t,uint32_t);\n")
string(REPLACE "loc_8213927C:" "loc_8213927C:\n{\n  const uint32_t counter_device=ctx.r31.u32;\n  const auto counter_writer=edf_native_begin_counter_reset_write(base,counter_device);" counter_body "${counter_body}")
string(REPLACE "\t// bne cr6,0x82139444" "  edf_native_complete_counter_reset_write(base,counter_device);\n}\n\t// bne cr6,0x82139444" counter_body "${counter_body}")
file(APPEND "${OUTPUT}" "#include \"native_graphics/native_buffer_writes.h\"\nedf::native::NativeBufferWrites::WriterScope edf_native_begin_counter_reset_write(uint8_t*,uint32_t);\nvoid edf_native_complete_counter_reset_write(uint8_t*,uint32_t);\n${counter_body}\n")
