# Keep D750's retail CPU decisions/updates/return intact. Only remove its
# isolated command-buffer rollover and two-word GPU packet emission.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.54.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213D750) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing derived render-state routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing derived render-state boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
# A boundary match alone cannot detect new CPU side effects in the removed
# block. Require re-audit if any normalized instruction in this routine changes.
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "7aef0ff05a164da9023b92ea614a9803e0390e481fed160142640e925d839edc")
    message(FATAL_ERROR "D750 changed; re-audit native CPU/packet separation")
endif()
string(FIND "${body}" "\t// ble cr6,0x8213d8a4" packet_begin)
string(FIND "${body}" "\t// b 0x8213d918" packet_end)
if(packet_begin LESS 0 OR packet_end LESS packet_begin)
    message(FATAL_ERROR "Derived render-state packet boundary changed")
endif()
string(SUBSTRING "${body}" 0 ${packet_begin} prefix)
string(SUBSTRING "${body}" ${packet_end} -1 suffix)
string(REPLACE "DEFINE_REX_FUNC(sub_8213D750)" "DEFINE_REX_FUNC(edf_native_derived_cpu_tail)" prefix "${prefix}")
file(WRITE "${OUTPUT}" "// Generated native derived CPU tail. Do not edit.\n#include \"edf2017_funcs.54.h\"\n${prefix}${suffix}\n")
