# ECB0's two inline packet regions also change CPU dirty bits. Retain those
# transitions and every other CPU operation; omit only GPU encoding/rollover.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.17.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213ECB0) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing main derived-state routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing main derived-state boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "8dac532746d2abbd5588ba9831006e55d52d9446c0f9bd74f4246dc9c219ba17")
    message(FATAL_ERROR "ECB0 changed; re-audit native CPU/packet separation")
endif()
# First region follows EAB0. Keep bit46 set and the10452 read consumed below.
string(FIND "${body}" "\t// lwz r10,48(r30)" first_begin)
string(FIND "${body}" "\t// lwz r11,24(r28)" first_end)
string(FIND "${body}" "loc_8213F0D4:" last_begin)
string(FIND "${body}" "loc_8213F348:" last_end)
if(first_begin LESS 0 OR first_end LESS first_begin OR last_begin LESS first_end OR last_end LESS last_begin)
    message(FATAL_ERROR "Main derived-state packet boundaries changed")
endif()
string(SUBSTRING "${body}" 0 ${first_begin} prefix)
math(EXPR middle_length "${last_begin}-${first_end}")
string(SUBSTRING "${body}" ${first_end} ${middle_length} middle)
string(SUBSTRING "${body}" ${last_end} -1 suffix)
string(REPLACE "DEFINE_REX_FUNC(sub_8213ECB0)" "DEFINE_REX_FUNC(edf_native_main_state_cpu_tail)" prefix "${prefix}")
set(first_cpu "\tctx.r20.u64 |= uint64_t(1)<<46;\n\tctx.r10.u64 = REX_LOAD_U32(ctx.r30.u32 + 10452);\n")
# The late region has no CPU stores. Its only retained effect is clearing bit3,
# and clearing bits47/48 when bit48 was dirty, under device10808 bit0x40.
set(last_cpu "loc_8213F0D4:\n\tif(REX_LOAD_U8(ctx.r30.u32 + 10808)&0x40) {\n\t\tctx.r20.u64 &= ~uint64_t(8);\n\t\tif(ctx.r20.u64 & (uint64_t(1)<<48)) ctx.r20.u64 &= ~(uint64_t(3)<<47);\n\t}\n")
set(native_body "${prefix}${first_cpu}${middle}${last_cpu}${suffix}")
# This function is already explicitly native. Do not dispatch through retail
# packet helpers and rely on a surrounding ownership scope to redirect them.
string(REPLACE "sub_8213EAB0(ctx, base);" "// Xbox program-load packet emission omitted." native_body "${native_body}")
string(REPLACE "sub_8213E950(ctx, base);" "__imp__edf_native_shader_upload_cpu_tail(ctx, base);" native_body "${native_body}")
string(REPLACE "sub_8213D750(ctx, base);" "__imp__edf_native_derived_cpu_tail(ctx, base);" native_body "${native_body}")
string(REPLACE "sub_8213EB68(ctx, base);" "__imp__edf_native_shader_cache_cpu_tail(ctx, base);" native_body "${native_body}")
file(WRITE "${OUTPUT}" "// Generated native main-state CPU tail. Do not edit.\n#include \"edf2017_funcs.17.h\"\nREX_EXTERN(__imp__edf_native_shader_upload_cpu_tail);\nREX_EXTERN(__imp__edf_native_derived_cpu_tail);\nREX_EXTERN(__imp__edf_native_shader_cache_cpu_tail);\n${native_body}\n")
