# Preserve C410's CPU cursor and observer callbacks, not GPU ring submission.
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.33.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213C410) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing ring submission routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing ring submission boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "8765c8b2c491d0c82d54160cca9251280cbfe37f820641c93ba31a344be20120")
    message(FATAL_ERROR "C410 changed; re-audit ring CPU/callback effects")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_8213C410)" "DEFINE_REX_FUNC(edf_native_ring_submit_cpu_tail)" body "${body}")
string(REPLACE "sub_8213BCE0(ctx, base);" "// No GPU ring capacity wait in native mode." body "${body}")
foreach(store "REX_STORE_U32(ctx.r10.u32 + ctx.r24.u32, ctx.r9.u32);"
              "REX_STORE_U32(ctx.r9.u32 + ctx.r24.u32, ctx.r31.u32);"
              "REX_STORE_U32(ctx.r10.u32 + ctx.r24.u32, ctx.r28.u32);"
              "REX_MM_STORE_U32(ctx.r11.u32 + 1812, ctx.r29.u32);")
    string(REPLACE "${store}" "// Native submission: no GPU ring write." body "${body}")
endforeach()
file(WRITE "${OUTPUT}" "// Generated native ring CPU tail. Do not edit.\n#include \"edf2017_funcs.33.h\"\n${body}\n")
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.31.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213BD90) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing ring copy routine")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing ring copy boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "0544fb55a39571ece444277ad0cb26bb6b12b6aa99194b0bb43948b61e1aba28")
    message(FATAL_ERROR "BD90 changed; re-audit ring copy CPU effects")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_8213BD90)" "DEFINE_REX_FUNC(edf_native_ring_copy_cpu_tail)" body "${body}")
string(REPLACE "sub_8213BCE0(ctx, base);" "ctx.r3.u64=(ctx.r31.u32+ctx.r29.u32)&ctx.r27.u32; // CPU return, no GPU capacity wait." body "${body}")
string(REPLACE "ctx.r10.u64 = REX_LOAD_U32(ctx.r11.u32 + 0);" "ctx.r10.u64 = 0; // Packet source is not consumed by native rendering." body "${body}")
string(REPLACE "REX_STORE_U32(ctx.r9.u32 + ctx.r26.u32, ctx.r10.u32);" "// No Xbox ring packet copy." body "${body}")
file(APPEND "${OUTPUT}" "#include \"edf2017_funcs.31.h\"\n${body}\n")
file(READ "${SOURCE_DIR}/generated/default/edf2017_recomp.19.cpp" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "DEFINE_REX_FUNC(sub_8213C9F0) {" begin)
if(begin LESS 0)
    message(FATAL_ERROR "Missing worker signal encoder")
endif()
string(SUBSTRING "${source}" ${begin} -1 tail)
string(FIND "${tail}" "\nDEFINE_REX_FUNC(" end)
if(end LESS 0)
    message(FATAL_ERROR "Missing worker signal boundary")
endif()
string(SUBSTRING "${tail}" 0 ${end} body)
string(SHA256 fingerprint "${body}")
if(NOT fingerprint STREQUAL "feb720408d49834c8742f51aca3078c1c237f1814893b32a5a132a61651c963f")
    message(FATAL_ERROR "C9F0 changed; re-audit signal CPU effects")
endif()
string(REPLACE "DEFINE_REX_FUNC(sub_8213C9F0)" "DEFINE_REX_FUNC(edf_native_worker_signal_cpu_tail)" body "${body}")
# Retain CPU reservation/ABI, not signal registers, GPU waits or interrupts.
string(REGEX REPLACE "REX_STORE_U32\\(ea, ctx.r[0-9]+\\.u32\\);" "// Native signal metadata is captured outside the guest stream." body "${body}")
# The two writeback-pointer reads only construct addresses for removed packets.
# Native signal ownership is supplied by the host queue, not a GPU writeback page.
foreach(reg r9 r11)
    string(REPLACE "ctx.${reg}.u64 = REX_LOAD_U32(ctx.r3.u32 + 10772);"
        "ctx.${reg}.u64 = 0; // No Xbox signal writeback address dependency." body "${body}")
endforeach()
file(APPEND "${OUTPUT}" "#include \"edf2017_funcs.19.h\"\n${body}\n")
