"""Authored execution instructions; imported by the coverage catalog generator.

Edit this file to improve a task. Do not edit generated catalog/guide text.
These instructions describe work to do, not verified implementation results.
"""

PLAYBOOKS = {}

def card(id, kind, files, symbols, first_slice, prerequisite, steps, cases, targets, avoid, stop):
    PLAYBOOKS[id] = dict(
        kind=kind, input_paths=files.split(), search_symbols=symbols,
        first_slice=first_slice, prerequisite_evidence=prerequisite,
        steps=steps, acceptance_cases=cases, test_targets=targets.split(),
        do_not=avoid, stop_condition=stop,
        deliverables=[
            'contract.csv: selected source locators, branch/receiver, inputs, writes/outputs, owner, lifetime, evidence and unresolved question.',
            'results.md: exact slice attempted, prerequisite evidence, changes/findings, commands with exit codes, acceptance cases passed/failed/not-run, and remaining scope.',
            'Epistemic evidence IDs and any confirmed claim IDs; negative results and unresolved assumptions must be included.',
        ])

card('R01.scope','investigation',
 'out/renderer-inventory/complete-function-inventory.csv out/renderer-inventory/root-manifest.csv out/renderer-inventory/generated-call-edges.csv out/renderer-inventory/indirect-site-ledger.csv',
 'sub_821A5080|sub_820B4310|sub_820B4250',
 'Classify one root-to-callee path starting at sub_821A5080. Select at most five functions from that path, not the first five unrelated CSV rows.',
 'No implementation prerequisite. The coverage audit must be current, and selected generated-code and Ghidra locators must exist.',
 ['Find the selected function in the function inventory; record root_reasons and incoming/outgoing direct edges in contract.csv.',
  'Read the native hook and generated PPC body for each selected function. Use the existing Ghidra body as an aid, and check disputed control flow against emitted instructions.',
  'For each branch, list render submission, simulation writes, resource operations and indirect targets. Assign renderer-consumer, producer, shared-utility or unresolved; a single function may have multiple roles.',
  'Record the exact mode/guard for any exclusion. Add a scoped follow-up for unknown callees/targets, then move to the next connected slice. Leave the package open until all assigned rows have evidence.'],
 ['A shared allocator reached from a renderer is classified as a utility with its caller obligations retained.',
  'An indirect call with a plausible vtable candidate stays unresolved without receiver/registration proof.',
  'Every selected function has both an incoming-path witness and a documented outgoing-boundary disposition.'],
 '',
 ['Do not port the 9,216-function closure wholesale.', 'Do not use class names, hook presence or absence of an __imp__ call as proof of ownership.'],
 'If a body is truncated or a target cannot be identified, save the last proven instruction/argument flow and the next precise lookup. Do not classify the path as unreachable.')

card('R01.callbacks','investigation',
 'src/native_graphics/native_frame_dispatch.h out/renderer-inventory/core-callback-candidates.csv out/renderer-inventory/startup-listener-registration.csv out/renderer-inventory/world-camera-factory-registration.csv',
 '821A5158|821A51D8|821A5264|821A5290|821A52A8|821A52E4|821A52F8|821A5368|821A3C50',
 'Resolve the scene-begin callback at 821A5158 (manager+132, slot1) from registration through removal before tackling the other eight sites.',
 'R01.scope must identify the selected callback as renderer-facing; full broad-closure triage is not required to investigate this site.',
 ['Record instruction, receiver expression, slot byte offset, argument values and candidate targets. Keep pointer verification separate from receiver membership.',
  'Trace all discovered writers of the receiver/list field and constructor vtable installs. Add registration, mutation and removal locators to the same row.',
  'Follow each candidate implementation through its render/producer boundary; retain mode guards for player, free, motion and base cameras and listeners.',
  'Compare with observed targets when R10.trace data exists. An unobserved but reachable candidate remains in scope. Deliver a nine-site table and explicit unresolved receiver questions.'],
 ['All eight outer sites and bucket site821A3C50 have rows.', 'Removal/re-registration and a changed receiver table cannot escape the candidate population silently.', 'An unknown runtime target creates a new task row instead of being discarded.'],
 'edf_native_frame_dispatch_tests',
 ['Do not replace the callback with a guessed class-specific target.', 'Do not treat one Mission1 trace as proof that other modes cannot register another receiver.'],
 'If receiver registration is missing, retain original dispatch for that site and hand off the exact receiver field and candidate writer search.')

card('R01.modes','investigation',
 'out/renderer-coverage/configuration-modes.csv src/native_graphics/guest_shader_bridge.cpp README.md docs/renderer-coverage-runtime.md',
 'edf_native_scene_backend|edf_native_seam_draws|edf_native_frame_dispatch',
 'Build the backend x recorded/direct-draw matrix first: D3D12, D3D11, WARP variants and empty backend.',
 'Use current setting definitions and actual consumer guards. R01.callbacks supplies known camera/listener modes; leave unknown mode populations explicit.',
 ['For each selected setting, read its definition, accepted range, restart requirement and every consumer guard; record literal default separately from accepted values.',
  'List compatible and incompatible combinations using the source guards, starting with backend and seam_draws. Record the existing rejection/migration behavior.',
  'Map supported combinations to scenario IDs and specific captures/tests. Mark unexecuted combinations untested, not unsupported.',
  'Repeat for cadence, workers, credits, MSAA, resolution/canvas, camera/player modes and ownership/debug switches. Propose any support-policy change separately from observed behavior.'],
 ['D3D12 plus direct D3D11-only draws has an explicit disposition backed by its guard.', 'Every one of the98 captured definitions has a value/guard/restart/test row.', 'Unsupported is justified by source or an explicit product decision; an absent test is recorded as untested.'],
 '',
 ['Do not silently change defaults or remove compatibility modes while cataloging them.', 'Do not enumerate the Cartesian product blindly; document guard-equivalent groups and pairwise choices.'],
 'If a requested support policy is not determined by source or existing project decisions, document the alternatives and impact; do not invent a supported/unsupported label.')

card('R02.publication','implementation',
 'src/native_graphics/guest_shader_bridge.cpp src/native_graphics/native_scene_adapter.h src/native_graphics/native_scene_sources.h src/native_graphics/native_model_pose_history.h tests/native_scene_tests.cpp',
 '820B4250|821A4DE8|Publish|generation',
 'Document and test the owner+364 counter and owner+356 time writes in820B4250 before moving any operation out of rendering.',
 'R01.callbacks identifies the selected producer/render route; R09.effects supplies its writes, readers and ordering. Do not move a write whose consumers are unknown.',
 ['Record before/after simulation fields and the publication point after821A4DE8. Identify which thread owns each mutation and which resource generation the data refers to.',
  'Define one immutable publication record with generation/tick ID and retained handles for the selected state. Specify how the consumer acquires it without combining generations.',
  'Move only proven simulation updates to the producer tick; make repeated rendering consume the same retained record without advancing those updates.',
  'Add repeat-render/new-tick tests before expanding the record to camera, animation and effects. Include a delayed consumer retaining the previous generation.'],
 ['Rendering one generation10 times leaves selected counters/time and authoritative poses byte-identical.', 'One new simulation tick applies the update once and publishes a new generation.', 'A producer update while an old frame is pending does not invalidate that frame or mix its inputs.'],
 'edf_native_scene_tests',
 ['Do not copy all live guest memory into a snapshot.', 'Do not move updates based only on a function name such as RenderWorld.'],
 'If simulation versus rendering ownership cannot be distinguished, keep that update in its current owner and return an evidence-backed contract question.')

card('R02.camera','implementation',
 'src/native_graphics/guest_shader_bridge.cpp src/native_graphics/native_camera_history.h src/native_graphics/native_scene_pass_inputs.h tests/native_scene_tests.cpp',
 '821CDDF8|821BE8D0|NativeCamera|projection',
 'Capture one player-view camera record and compare its view/projection bytes with the current path at a locked simulation tick.',
 'R02.publication must provide a generation and retention contract for this view. Resolve dimensions/FOV and matrix operation order before replacing derivation.',
 ['Trace view/projection/FOV/viewport producers and distinguish authoritative source pose from derived matrices.',
  'Store the selected per-view camera inputs and derived values in the publication; use a view identity so a second view cannot overwrite the first.',
  'Preserve audited floating-point operation order and scoped source-pose restoration. Add interpolation as a consumer operation over two retained generations.',
  'Compare locked/unlocked, zoom and view changes against the reference path, recording any intentional numeric tolerance and its reason.'],
 ['Repeated rendering does not alter authoritative camera pose/FOV.', 'Two views with different projection/viewport retain separate values.', 'Zoom, dimension changes and invalid dimensions follow an explicit policy and do not introduce silent NaNs or changed rounding.'],
 'edf_native_scene_tests',
 ['Do not recompute projection with an algebraically equivalent formula without checking float rounding.', 'Do not import a live viewport after selecting an older camera generation.'],
 'If a camera mode lacks a known producer or identity, preserve its current path and leave that mode open.')

card('R03.selection','implementation',
 'src/native_graphics/native_scene_tree_publication.h src/native_graphics/native_scene_membership.h src/native_graphics/native_scene_visibility.h src/native_graphics/native_scene_sources.h tests/native_scene_tests.cpp',
 '821C61D8|820B4038|821BEE68|821C3BB8|hidden|duplicate',
 'Select one static leaf containing two ordered objects and publish all inputs used to accept/reject those objects.',
 'R02.publication supplies a retained generation; R09.effects identifies writers of hidden/mode/duplicate/LOD inputs for this leaf.',
 ['Read the current selector and list every guest-memory field it reads, including inherited flags and duplicate bookkeeping.',
  'Trace writers for missing fields; add fields to the same publication as hierarchy and ordered membership, rather than fetching them later.',
  'Run selection against only that retained generation; defer live mutations to a new generation through the established producer contract.',
  'Add exact selected-ID/order comparisons and a guard that detects guest selection reads. Expand to hierarchy and LOD boundaries after the leaf fixture passes.'],
 ['Hidden/visible, LOD threshold and duplicate cases return the expected IDs in the expected order.', 'Remove/reinsert and same-address new lifetime do not select stale objects.', 'Changing live guest fields after publication does not change selection of that publication.'],
 'edf_native_scene_tests',
 ['Do not mix retained membership with current adapter records.', 'Do not treat an empty scene or zero audit checks as a passing comparison.'],
 'If a required field has no known writer, keep that selection route explicit and request a writer investigation instead of reading it live inside the native consumer.')

card('R03.mutation','implementation',
 'src/native_graphics/guest_shader_bridge.cpp src/native_graphics/native_scene_membership.h src/native_graphics/native_scene_tree_publication.h out/renderer-inventory/indirect-site-ledger.csv tests/native_scene_tests.cpp',
 '821C0C00|Invalidate|mutation|fallback',
 'Reproduce one callback that removes or changes the next object during leaf traversal.',
 'R01.callbacks identifies the chosen target and mutation contract; R03.selection gives the immutable traversal behavior to preserve.',
 ['Find the821C0C00 fallback and record when it invalidates, calls original code and refreshes live state.',
  'Build a fixture for mutation during traversal: next removal, current removal, insertion or target replacement. Write the required order/visibility result before changing behavior.',
  'Choose an explicit contract consistent with producers: retain the current generation, or abort/defer and republish. Keep guest-pointer validation boundaries around callbacks.',
  'Replace only the proven live fallback route and expose a reason counter for any remaining unsupported route. Check reuse after removal.'],
 ['Removing the next node neither dereferences freed memory nor skips an unrelated retained node.', 'New insertions appear only in the defined generation/order.', 'Unknown callbacks cannot silently restart traversal over mutable live links.'],
 'edf_native_scene_tests',
 ['Do not continue with cached live pointers after a guest callback.', 'Do not swallow an unsupported callback and count the object as rendered.'],
 'If callback mutation semantics differ by mode, retain separate explicit mode branches until each has evidence.')

card('R04.pass','implementation',
 'src/native_graphics/guest_shader_bridge.cpp src/native_graphics/native_scene_handoff.h src/native_graphics/native_scene_material.h src/native_graphics/native_scene_pass_inputs.h out/renderer-inventory/static-pass-contracts.csv tests/native_scene_tests.cpp',
 '821D96D8|821B94E8|821B8E48|indexed_cpu_tail',
 'Render one retained static group including geometry, material and world transforms while counting every legacy setup/activation/tail call it makes.',
 'Selected group has R03.mutation selection semantics, R05.pass inputs, R09.effects CPU-effect ownership and R09.retirement lifetime/queue contracts.',
 ['Make a before/after table of every retained call for the group. Separate required CPU writes from packet emission and actual native submission.',
  'Move required writes to their documented producer/native owner; keep ordering and retirement operations even when packet emission is removed.',
  'Submit the group from retained handles and explicit pass inputs. Add a fixture guard that fails if legacy setup/activation/draw submission runs for the selected supported group.',
  'Compare output and state with the reference, then expand to multiple materials and mixed static/animated ordering. Keep unsupported groups counted and assigned.'],
 ['Nonempty supported static pass renders while guarded legacy consumer calls remain zero.', 'A material boundary preserves inherited state needed by the following draw.', 'Retiring a resource after publication does not break the in-flight frame; address reuse does not revive it.'],
 'edf_native_scene_tests edf_native_immediate_tail_tests',
 ['Do not equate removing a draw call with removing its CPU side effects.', 'Do not add a new ownership flag without implementing the complete selected boundary.'],
 'If a retained CPU write lacks an owner/reader contract, stop removing that call and return the exact missing effect to R09.effects.')

card('R05.pass','implementation',
 'src/native_graphics/native_scene_pass_inputs.h src/native_graphics/guest_shader_bridge.cpp out/renderer-inventory/pass-format-contracts.csv out/renderer-inventory/untiled-boundary-contracts.csv tests/native_scene_tests.cpp',
 '821BE8D0|821BE9D8|8219C5A8|8219C840|viewport|resolve',
 'Describe one ordinary gameplay begin/end pair and the loading direct-scene end path before changing target inheritance.',
 'R02.camera provides retained per-view inputs and R09.resources defines target identity/retention. Existing pass-contract rows remain partial until their remaining obligations are resolved.',
 ['Record target color/depth handles, formats, sample count, viewport, scissor, clear values, resolve source/destination and entry/exit CPU writes.',
  'Create an explicit pass record that contains every currently inherited input and a defined output-state handoff to the next pass.',
  'Apply begin/draw/end/resolve using that record. Preserve required producer dirty-state effects separately from removed rendering packets.',
  'Add nested/offscreen and loading fixtures, then test resize/recreation with old pass records still retained.'],
 ['Nested pass B returns to the required A target/state without reading unrelated current guest state.', 'Loading with no active output still produces an eligible correctly owned direct-scene frame.', 'MSAA resolve and resource recreation preserve matching extent/format/lifetime.'],
 'edf_native_scene_tests edf_native_backend_compositor_tests',
 ['Do not import the most recently bound target as the owner of an older pass.', 'Do not restore Xbox tile replay as a compatibility shortcut.'],
 'If begin/end ownership differs between direct-scene and normal output, document both routes and leave the unproven route open.')

card('R05.post','investigation-and-implementation',
 'src/native_graphics/effect.cpp src/native_graphics/guest_shader_bridge.cpp docs/native-renderer-migration.md tests/native_display_gamma_tests.cpp',
 'Tone|MiddleGray|Luminance|post|bloom|gamma',
 'Identify one actual post technique and capture its input scene-color and output for the same frame.',
 'R05.pass gives target order/lifetime; R09.assets gives the selected effect identity and reflected parameters. A descriptive label such as bloom is not an identity.',
 ['Record effect/technique/pass identifiers, shader fingerprints, samplers, constants and target formats from source/assets.',
  'Trace authored environment values through upload to the native bindings. Distinguish tone-map/gamma/display transforms and their order.',
  'Capture paired inputs/outputs and compare with a matched reference at720p before changing arithmetic or viewport offsets.',
  'Fix only demonstrated differences, add focused parameter/output tests, then repeat for1080p and relevant MSAA/preset variants.'],
 ['Paired captures use the same frame and correctly labeled linear/HDR/display spaces.', 'Authored preset transitions change only the intended parameters.', 'Resolution/MSAA changes preserve sampling alignment, output extent and gamma order.'],
 'edf_native_effect_tests edf_native_display_gamma_tests',
 ['Do not tune authored tone constants by eye to hide a binding/order defect.', 'Do not claim HDR fidelity from a clamped BMP.'],
 'If no matched reference or actual technique identity is available, deliver the technique/parameter table and keep visual equivalence untested.')

card('R06.pose','implementation',
 'src/native_graphics/native_model_pose_history.h src/native_graphics/guest_shader_bridge.cpp out/renderer-inventory/content-boundary-contracts.csv tests/native_scene_tests.cpp',
 '821C9478|821C9C20|821B2C28|821A1738|821A17D8',
 'Build one rigid-model record and one two-bone skinned record; enumerate their original traversal/upload calls.',
 'R02.publication supplies a tick/generation; R09.effects supplies upload dirty-state and traversal contracts; R09.resources supplies retained mesh ownership.',
 ['Record model-record layout, matrix-index selection, skinning branch, palette size and draw order from the original traversal.',
  'Publish immutable model draw records and copied/retained matrix arrays with explicit lifetime. Separate authoritative bones from interpolated render poses.',
  'Implement native traversal/upload for the two fixtures and guard their original model-render calls. Preserve any required CPU upload mirrors in their declared owner.',
  'Extend to attachments and mixed skinned/unskinned records, then validate interpolation across two ticks with source bones unchanged.'],
 ['Rigid records choose the correct matrix; skinned records upload the expected palette and draw order.', 'Repeated interpolated frames leave source bones byte-identical.', 'Palette replacement/removal while an older frame is pending never uses released storage.'],
 'edf_native_scene_tests',
 ['Do not call original model traversal and label pose interpolation as full ownership.', 'Do not retain a pointer to a mutable guest palette without a lifetime contract.'],
 'If a record flag or matrix upload side effect is unknown, keep that branch open and request its exact local-effect contract.')

card('R06.families','investigation-and-implementation',
 'out/renderer-inventory/renderable-method-review.csv out/renderer-inventory/renderable-content-routes.csv out/renderer-inventory/renderable-helper-routes.csv src/native_graphics/guest_shader_bridge.cpp tests/native_scene_tests.cpp',
 '820DEA08|8210E6C0|8219A2D0|821E2250|821E5810',
 'Choose the soldier/player method sub_820DEA08 and one supported concrete receiver. Finish its route before selecting another family.',
 'R01.callbacks proves that receiver can reach the method; R06.pose provides the retained rigid/skinned consumer used by its draws.',
 ['Find the method row and enumerate its direct/helper/indirect route to draw submission; note class labels as provisional until receiver evidence exists.',
  'Record family-specific visibility, attachment, material, pose, topology and pass overrides; compare them with the shared model contract.',
  'Implement only the missing overrides around the shared native consumer and create a fixture for each distinct branch.',
  'Choose a mission/scenario that actually instantiates the receiver and collect route plus image evidence. Repeat per method, including multipart enemies and vehicles.'],
 ['The selected receiver reaches the expected native consumer without original render traversal.', 'Attachments retain parent/child pose and ordering across LOD/removal.', 'Each method/class row is tested or retains a precise unresolved/unvisited disposition.'],
 'edf_native_scene_tests',
 ['Do not assume all classes sharing a method share all runtime overrides.', 'Do not mark an entire family complete from one visible soldier.'],
 'If no reproducible scenario or registration proof exists for a family, deliver its static contract and leave runtime acceptance open.')

card('R07.effects','investigation-and-implementation',
 'out/renderer-inventory/renderable-method-review.csv out/renderer-inventory/renderable-content-routes.csv src/native_graphics/guest_shader_bridge.cpp src/native_graphics/native_scene.h tests/native_scene_tests.cpp',
 '8211D250|82121848|821897A8|8217D6E0',
 'Trace one muzzle-flash or particle method to geometry, sort key, material parameters and lifetime update.',
 'R02.publication owns effect time; R05.pass owns blend/depth/pass context; R09.dynamic retains transient geometry bytes.',
 ['Separate effect simulation (spawn/age/expiry) from geometry preparation and rendering; document exact input fields and writers.',
  'Publish geometry, material, transform, depth/sort order and lifetime identity at the producer tick.',
  'Render retained records in the original required transparent/additive order without advancing age; retain buffers until completion.',
  'Compare controlled firing and overlapping effects before expanding to trails, smoke, sparks, glass and projectile families.'],
 ['Ten renders of one tick do not age or expire an effect.', 'Two overlapping alpha effects preserve the required draw order; additive paths keep their own state.', 'Expiry/removal and buffer reuse do not leak old effects into later frames.'],
 'edf_native_scene_tests edf_native_quad_tests',
 ['Do not assume all transparency can be sorted by distance.', 'Do not infer a specific particle method from smoke pixels alone.'],
 'If sort key, spawn owner or lifetime writer is unknown, preserve the route and record that exact prerequisite.')

card('R07.environment','investigation-and-implementation',
 'out/renderer-inventory/renderable-method-review.csv out/renderer-inventory/renderable-helper-routes.csv src/native_graphics/native_scene_geometry.h src/native_graphics/native_scene_membership.h tests/native_scene_tests.cpp',
 '820B8D28|820BB270|820BBA48|82172698|8211FAA8|82120168',
 'Choose one special method, preferably sky sub_820BB270 or broken-piece sub_82120168, and record how it differs from a static group.',
 'R03.selection and R04.pass define retained static behavior; R09.dynamic covers any mutable topology or transient vertex storage.',
 ['Trace the selected method through helpers to topology/material/pass setup and submission; record any object removal or destruction side effects.',
  'Express its deviations as explicit retained inputs rather than extra live guest reads in the static pass.',
  'Implement the special draw path and lifecycle transition, with fixtures for visibility and retirement.',
  'Repeat for wire, rocks, trees, grass and destruction families; use actual environment/mission evidence to exercise each.'],
 ['Sky/vegetation state does not leak into the following ordinary world draw.', 'Destruction removes the intact draw and retains debris for its documented lifetime.', 'Same-address replacement and LOD/cull changes do not show stale parts.'],
 'edf_native_scene_tests',
 ['Do not force line/ribbon/debris topology through a triangle-only static contract.', 'Do not close all environment families from a city capture.'],
 'If a special family uses an unidentified helper or geometry writer, add that bounded investigation before changing its rendering.')

card('R07.shadows','investigation-and-implementation',
 'src/native_graphics/guest_shader_bridge.cpp src/native_graphics/effect.cpp docs/native-renderer-migration.md out/renderer-inventory/renderable-content-routes.csv',
 'shadow|Shadow|depth|stencil',
 'Identify one real shadow-producing technique/pass and its caster/receiver route; the initial slice is investigation only.',
 'R01.callbacks supplies renderer routes and R05.pass supplies pass identities. R06.pose is needed only when migrating animated casters.',
 ['Search effect techniques, reflected parameters, depth/stencil/target setup and caster-related routes. Record positive and negative search results.',
  'Trace a candidate from producer through draw to the sampled/receiver pass; distinguish actual shadows from baked texture shading or other darkening.',
  'Capture a controlled stationary/moving caster and receiver pair with candidate pass counters. If no technique is found, bound the searched modes/assets instead of claiming global absence.',
  'Only after identification, publish the caster/receiver inputs and migrate the complete pass; add occlusion and animated-caster tests.'],
 ['The pass identity is linked to target writes and receiver use, not just a symbol name.', 'Moving a caster changes the expected receiver shadow in a matched reference.', 'Absence claims state an exact asset/mode search scope and retained unknowns.'],
 'edf_native_scene_tests edf_native_effect_tests',
 ['Do not invent a shadow-map implementation before identifying the game technique.', 'Do not use a dark screenshot region as sole proof of shadow coverage.'],
 'If the actual shadow technique cannot be identified, stop at a reproducible search report and a precise next producer/pass query.')

card('R07.special','investigation',
 'out/renderer-inventory/renderable-method-review.csv out/renderer-inventory/verified-vtable-pointers.csv out/renderer-inventory/renderable-table-installations.csv out/renderer-inventory/renderable-constructor-review.csv',
 '8252B718|8210E220|821E5558',
 'Select one concrete class table pointing to8252B718; follow its constructor and other render-related slots.',
 'R01.scope identifies the table/function slice; R01.callbacks provides known receiver-registration routes.',
 ['Confirm the slot pointer against the verified table row and local body; record the distinction between a no-op method and a no-render object.',
  'Find constructor installations, concrete subclasses and other render/producer callbacks that may perform the visible work.',
  'Trace registration/removal and mode activation. For debug/test objects, determine whether the audited build can construct/register them.',
  'Assign each selected class no-op-slot, alternate-render-route, producer-only or unresolved with evidence; repeat for all shared/base/test rows.'],
 ['A no-op slot with another rendering slot is not classified as a non-rendering family.', 'A claimed unreachable debug route has constructor/registration/mode evidence.', 'Every class sharing the method receives its own disposition or a justified shared contract.'],
 '',
 ['Do not delete classes or callbacks based on a no-op local body.', 'Do not import external port-complete labels as evidence.'],
 'If concrete construction or registration is unknown, keep the class unresolved with the exact table/slot and missing writer.')

card('R08.ui','implementation',
 'src/native_graphics/guest_shader_bridge.cpp src/native_graphics/native_xui_bindings.h src/native_graphics/font_effect.cpp src/native_graphics/native_canvas_constants.h tests/native_xui_tests.cpp tests/native_ui_tests.cpp',
 '820D3FD0|RenderOverlay|RenderUiListener|Xui|font',
 'Publish and replay one HUD/text layer at a fixed camera/tick, recording its position in final composition.',
 'R01.callbacks identifies overlay/listener receivers; R05.pass provides target/clip state; R09.assets covers the selected font/XUI material contract.',
 ['Trace UI production separately from rendering. Record texture/font handles, authored canvas coordinates, clip/scissor, layer order and parameters.',
  'Build retained draw records for the selected layer, preserving update cadence and references until the frame finishes.',
  'Render the layer through native UI submission with original consumer calls guarded; compare final composed output, not only intermediate scene color.',
  'Expand to radar/crosshair, menus/pause/results and SDK overlay, then verify canvas transforms at720p/1080p and alternate aspect.'],
 ['Text, radar and crosshair stay in the expected layer and clip region.', 'Pause and SDK overlays cover the intended game content without corrupting its target.', 'Authored1280x720 coordinates scale consistently at native1080p with no double scaling.'],
 'edf_native_xui_tests edf_native_ui_tests edf_native_backend_sdk_ui_tests',
 ['Do not move menu/gameplay state updates into repeated render execution.', 'Do not accept partial output captures as final UI composition proof.'],
 'If font/texture lifetime or listener ordering is unknown, preserve that layer and document the missing contract.')

card('R08.loading','implementation',
 'src/native_graphics/guest_shader_bridge.cpp src/native_graphics/native_backend_frame_queue.h tools/start-native-binding-validation.ps1 docs/renderer-coverage-runtime.md',
 '8219C840|direct_scene|loading|submissions',
 'Reproduce the no-active-output loading branch and link its eligibility counter to an actually published and presented sequence.',
 'R05.pass and R08.ui supply direct-scene/UI composition; R09.retirement supplies old-generation drain rules. Readiness alone is not publication success.',
 ['Record menu-to-load-to-gameplay states, active target/output identities, thread ownership and submission-lock intervals.',
  'Add or use sequence evidence for eligibility, publication, acquisition and presentation; identify any dropped/blocked stage.',
  'Fix the selected output/locking/lifetime defect while preserving loader producer work; do not hold the shared submission gate across pacing sleep or unrelated completion waits.',
  'Exercise cold/warm load, retry, menu return and another mission; retain queue peaks and old/new resource generation evidence.'],
 ['Loading frames actually present while no ordinary output exists.', 'Queue/upload memory remains bounded during a slow load.', 'Retry or next mission does not consume resources from the retired map generation.'],
 'edf_native_backend_compositor_tests edf_native_host_lifetime_tests',
 ['Do not interpret cumulative XUI/font counts as per-frame visible progress.', 'Do not change scene ownership merely to suppress a black-frame log.'],
 'If the scenario cannot reach loading deterministically, fix/record R10.input readiness first; do not mark the transition passed.')

card('R08.movie','implementation',
 'src/native_graphics/native_movie_bindings.h src/native_graphics/movie_effect.cpp src/native_graphics/guest_shader_bridge.cpp tests/native_movie_tests.cpp',
 'movie|Movie|YUV|plane',
 'Trace one decoded movie frame from plane production through native conversion to the host frame.',
 'R05.pass identifies the movie composition target; R09.resources defines plane ownership and upload lifetime.',
 ['List format, dimensions, pitch/stride, YUV/RGB conversion constants, producer thread and plane reuse point.',
  'Retain or copy the planes and parameters as one frame identity until the consumer/GPU finishes; keep decoder production separate.',
  'Implement/verify native conversion and composition with correct topology and color range; compare a known decoded input and matched output.',
  'Exercise skip/end while frames are queued, then repeat for supported SD/HD variants and menu transition.'],
 ['All planes belong to the same decoded frame and retain correct pitch/extent.', 'Known color samples agree with the documented conversion/range.', 'Skip/end drains or cancels pending frames without presenting a stale movie frame over the menu.'],
 'edf_native_movie_tests edf_native_backend_compositor_tests',
 ['Do not overwrite decoded plane memory still referenced by a queued draw.', 'Do not claim SD/HD coverage from a cumulative movie counter.'],
 'If a movie variant or decoded reference is unavailable, leave that variant untested and deliver the known format/lifetime contract.')

card('R08.present','implementation',
 'src/native_graphics/native_backend_host.cpp src/native_graphics/native_host_surface.cpp src/native_graphics/native_backend_frame_queue.h src/native_graphics/native_backend_present.cpp tests/native_host_lifetime_tests.cpp',
 '820B0B80|Present|resize|sequence|completion',
 'Trace one published frame through acquisition, GPU copy, Present and surface release, including its sequence IDs.',
 'R05.pass owns final output, R09.sync defines completion waits and R09.retirement defines release timing. Include host integration outside native_graphics when following call sites.',
 ['Write the surface-ring state transitions and ownership at each stage. Identify original finish callbacks and required CPU effects.',
  'Remove only render-consumer dependence already covered by those contracts; retain surface references through copy/presentation completion.',
  'Handle resize/minimize/restore/shutdown by draining or invalidating the correct generation; make device-loss recovery or explicit failure policy visible.',
  'Compare submitted/acquired/presented sequence IDs and complete-frame captures during transitions. Investigate repeats/drops by stage.'],
 ['No surface is reused before the consuming GPU operation completes.', 'Resize/restore presents the new extent without dangling old targets.', 'Shutdown releases only owned resources and cannot deadlock on an unpublished or canceled frame.'],
 'edf_native_backend_host_tests edf_native_host_lifetime_tests edf_native_present_tail_tests',
 ['Do not equate calling Present with a new rendered image.', 'Do not remove finish callbacks until their CPU/lifetime effects are assigned.'],
 'If device-loss behavior is not implemented or reproducible, record the actual failure policy and leave recovery acceptance open.')

card('R09.effects','investigation',
 'out/renderer-inventory/retained-call-effect-reviews.csv out/renderer-inventory/macro-original-dependencies.csv out/renderer-inventory/retained-adapter-terminal-edges.csv out/renderer-inventory/state-write-ledger.csv',
 '821D96D8|821BE9D8|82141440|82149608',
 'Choose one explicit retained call required by R04.pass; review its complete connected CPU effect contract before selecting another callee.',
 'R01.scope proves the selected call matters to a renderer route. Reuse existing partial local-effect evidence instead of restarting decompilation.',
 ['Record branch guard, arguments, return use and already reviewed local writes. Mark local versus transitive evidence separately.',
  'Follow outgoing calls and pointer aliases far enough to assign every relevant write, callback, allocation, release, lock and failure effect; include vector/atomic/zero-fill operations.',
  'For each destination, identify reader, lifetime and required ordering; assign simulation producer, resource producer, native consumer or compatibility-only owner.',
  'Deliver a contract and a differential fixture specification; implement a fixture when needed to resolve disputed behavior. Repeat by selected callee, not by every raw store row independently.'],
 ['No required CPU write disappears merely because packet emission is unnecessary.', 'Aliased memory, callback writes and failure-after-partial-write are represented in the contract.', 'Stack-only disposition has alias/escape evidence; unknown transitive effects keep the call open.'],
 '',
 ['Do not count87,579 store candidates as87,579 implementation tasks.', 'Do not upgrade a partial local review to complete callee semantics.'],
 'If a helper/provider is unresolved, record exact callsite, arguments and consumer obligation; do not delete or bypass the retained call.')

card('R09.resources','investigation-and-implementation',
 'src/native_graphics/native_model_buffers.h src/native_graphics/native_buffer_writes.h src/native_graphics/guest_shader_bridge.cpp out/renderer-inventory/native-original-references.csv tests/native_scene_tests.cpp',
 'ImportTexture|82201458|NotifyUpdateAliases|ObservedVersion|CommitObserved',
 'Choose one VB/IB owner and trace create, publish, update, retire and same-address replacement before reviewing other resource kinds.',
 'R09.effects supplies the selected allocator/lock/unlock/destructor effects and the physical/virtual alias relationship.',
 ['Write a lifecycle table with resource identity, lifetime ID, revision, aliases, producer and retained native handle.',
  'Trace every known mutation route including import callback82201458, unlock, guest writes and free/reallocation; distinguish identity change from content revision.',
  'Fix or specify the observed-version handshake so a snapshot commits only if the owner/lifetime/revision still match; retain old handles for pending consumers.',
  'Add create/update/failure/reuse tests and repeat for textures, declarations and shaders. Attribute untracked writers to a named follow-up.'],
 ['Same address with a new lifetime never reuses stale native bytes or metadata.', 'An alias update invalidates all overlapping published owners it is required to affect.', 'Failed allocation/import does not publish a partially initialized resource or leak a retained reference.'],
 'edf_native_scene_tests edf_native_guest_memory_tests',
 ['Do not replace lifetime identity with an address-only cache key.', 'Do not assume CPU-only heap placement without verifying the relevant allocation route.'],
 'If a write route bypasses revision tracking, keep that resource on the explicit validated path until its writer is incorporated.')

card('R09.retirement','investigation-and-implementation',
 'src/native_graphics/native_index_binding.h src/native_graphics/native_texture_binding.h src/native_graphics/native_shader_binding.h out/renderer-inventory/retirement-owner-provenance.csv out/renderer-inventory/small-retained-contracts.csv',
 '82141440|RetireNativeBoundResource|10780|10784|13148',
 'Follow one texture/shader unbind through immediate-fence tagging or the eight-byte retirement queue, including queue exhaustion.',
 'R09.effects must provide the queue writer and allocator-call contracts. Queue consumption and GPU completion are separate facts to establish.',
 ['Record queue record layout, old-resource predicate, preserved tag inputs, cursor/capacity and allocation-growth behavior.',
  'Find the queue consumer and the event/fence that makes release safe; trace reference ownership through failure and same-pointer rebind.',
  'Create differential fixtures for both retirement branches and allocator exhaustion before changing ownership code.',
  'Preserve observable ordering, alias writes and failure effects; test delayed completion and same-address reuse across pending frames.'],
 ['Queue-full handling preserves every record and the observed tag bits.', 'Immediate retirement and deferred retirement follow the correct predicates.', 'Rebinding the same pointer or retiring aliased memory does not change the original required write order.'],
 'edf_native_shader_binding_tests edf_native_backend_completion_tests',
 ['Do not zero an apparently uninitialized tag input that the original preserves.', 'Do not infer the queue is unused because one gameplay run did not fill it.'],
 'If the queue consumer or allocator ownership cannot be proved, keep retirement behavior and report the precise missing release condition.')

card('R09.shader','investigation-and-implementation',
 'src/native_graphics/native_shader_binding.h tests/native_shader_binding_tests.cpp out/renderer-inventory/small-retained-contracts.csv src/native_graphics/guest_shader_bridge.cpp',
 'ReadNativeShaderDefaults|SetNativeShaderResource|82149608|821498C8',
 'Add a fixture where an early constant write aliases a later defaults payload word; compare incremental original reads against the current collected-word parser.',
 'R09.retirement provides retirement ordering and alias semantics. The earlier retirement-before-default-read fix is baseline behavior to preserve.',
 ['Read the pixel/vertex original contracts and existing tests. List the three stream phases and exact read/write/failure sequence.',
  'Construct the smallest valid aliased stream that distinguishes incremental reads from precollection; record expected memory mutations at each step.',
  'Determine whether reachable providers permit the alias or malformed input. Fix reachable parity differences, or document a proven provider precondition; never infer safety from absence in a sample.',
  'Extend tests for null shader, absent defaults, pixel/vertex dirty stores and failure after partial application. Keep the previous retirement alias regression passing.'],
 ['Retirement still precedes binding/default sampling in the required order.', 'Payload self-alias behavior matches the justified contract.', 'Malformed count/extent behavior has an explicit reachable-input policy and tests, including already-applied writes when required.'],
 'edf_native_shader_binding_tests',
 ['Do not combine the two pixel dirty stores without an equivalence argument.', 'Do not simply remove bounds validation to mimic malformed loops.'],
 'If malformed or aliasing inputs have no established provider contract, deliver the failing differential case and precise reachability question before choosing behavior.')

card('R09.dynamic','implementation',
 'src/native_graphics/native_upload_ring.h src/native_graphics/native_buffer_writes.h src/native_graphics/guest_shader_bridge.cpp tests/native_upload_ring_tests.cpp tests/native_quad_tests.cpp',
 'immediate|transient|append|ring|quad',
 'Trace one immediate quad or effect vertex buffer from producer write through upload-ring allocation and GPU completion.',
 'R09.resources supplies identity/revision and release rules for the selected transient owner.',
 ['Record byte extent, stride/topology, index use, producer writer and all consumers of the mutable buffer.',
  'Snapshot or retain immutable bytes before the producer can reuse them; attach the snapshot to the publication/frame identity.',
  'Reserve ring space with explicit completion ownership and implement wrap/split behavior without overwriting pending uploads.',
  'Stress append, wraparound, concurrent publication and large effect bursts; feed encountered formats into the contract catalog.'],
 ['A producer rewrite after publication cannot change the older queued draw.', 'Ring wrap waits/splits or allocates according to policy instead of overwriting pending data.', 'Large bursts report bounds/rejections explicitly and preserve draw order.'],
 'edf_native_upload_ring_tests edf_native_quad_tests edf_native_scene_tests',
 ['Do not retain a naked pointer to scratch memory across a producer update.', 'Do not treat a successful allocation as proof of safe GPU reuse.'],
 'If completion ownership for a transient block is unknown, keep its existing synchronized path and resolve that owner first.')

card('R09.sync','investigation-and-implementation',
 'out/renderer-inventory/retained-callback-review.csv out/renderer-inventory/worker-registration-review.json out/renderer-inventory/sdk-monitor-provenance.json src/native_graphics/guest_shader_bridge.cpp tests/native_worker_callback_audit_tests.cpp',
 '8243A000|8213C9F0|82134408|8214EBA0|KfAcquireSpinLock',
 'Choose one worker registration mode and follow its callback/context pair from writer to invocation and shutdown.',
 'R01.scope distinguishes renderer-relevant callbacks; R09.effects provides local lock, signal and event mutations.',
 ['Record registration mode, callback/context fields, writers, invocation guard, thread and lock held at each stage.',
  'Resolve alternate targets and external monitor/profiling callbacks separately; enumerate lock access/caller combinations instead of generalizing one audited caller.',
  'Draw a lock-order and signal/wait table, including exception/cancellation/shutdown paths. Implement only the selected proven owner transition.',
  'Add contention, missing-callback, alternate-mode and shutdown fixtures. Use bounded waits so a deadlock produces a recorded failed test.'],
 ['Callback/context publication cannot mix two registrations under the documented synchronization.', 'Every selected signal has a corresponding wait/completion contract, including failure paths.', 'Shutdown and contended execution complete within the fixture deadline without leaked locks.'],
 'edf_native_worker_callback_audit_tests edf_native_backend_completion_tests',
 ['Do not remove a lock because sampled single-threaded gameplay worked.', 'Do not classify SDK synchronization imports as renderer packet tails.'],
 'If an external callback population is unavailable, preserve it and record provider/registration requirements; do not substitute a no-op.')

card('R09.assets','investigation-and-implementation',
 'docs/native-coverage.md src/native_graphics/native_contract_ledger.h tools/native_texture_check.cpp tests/native_effect_tests.cpp tests/fixtures/geometry-contract-mission1.txt',
 'coverage|contract|rejected|declaration|technique',
 'Replay the existing Mission1 declaration fixture with the documented effect catalog, recording the exact corpus identity and accepted/rejected totals.',
 'R01.modes defines which backend/format combinations are in scope. Inspect the documented checker invocation before running it; do not invent asset paths or flags.',
 ['Read native-coverage.md and the checker/test argument parser. Record asset root, corpus hashes, command, omissions and failure counters.',
  'Enumerate technique render-state combinations and compare with native decoding/binding support, not merely shader compilation.',
  'Implement additive catalog merge with stable contract identity and provenance; retain rejected records and report newly seen combinations.',
  'Add offline replay for one uncovered path (immediate/font/movie/XUI/utility) at a time and associate runtime captures with mission/weapon/menu scope.'],
 ['Merging two catalogs preserves their union and reports new/rejected contracts without duplication.', 'Intentionally unsupported declaration/state is reported as a rejection, not silently omitted.', 'Zero failures identifies the exact closed asset set; runtime declaration exhaustion is not inferred.'],
 'edf_native_effect_tests edf_native_texture_tests',
 ['Do not erase rejected contracts to obtain a clean summary.', 'Do not call Mission1 the complete runtime declaration corpus.'],
 'If assets/checker binaries or a variant are missing, record the exact prerequisite and keep that coverage axis untested.')

card('R09.compat','investigation-and-implementation',
 'out/renderer-inventory/native-dependency-classification.csv out/renderer-inventory/macro-original-dependencies.csv out/renderer-coverage/configuration-modes.csv src/native_graphics/guest_shader_bridge.cpp',
 'ownership|fallback|EDF_RENDER_PHASE|EDF_RENDER_STATE_SETTER',
 'Choose one ownership-predicate fallback and exercise both sides using a valid fixture for its exact guard.',
 'R01.modes supplies supported-mode intent; R09.effects supplies the retained original call effects. Unproven policy changes are proposals, not defaults to change.',
 ['Record branch predicate, effective settings, selected original/native route and required post-state for the chosen callsite.',
  'Use fixtures to enter each guard outcome; confirm failure/unsupported cases remain visible and correctly owned.',
  'If replacing a supported route, preserve CPU effects and add route attribution. If rejecting an unsupported route, use the agreed policy and an explicit diagnostic.',
  'Repeat for host/bridge/activation-disabled and diagnostic paths, preserving macro forwarding classifications.'],
 ['Both native and retained branches produce the documented required CPU state.', 'Unsupported configuration cannot silently enter an unowned renderer.', 'Diagnostic-only branches are labeled and do not falsely count toward native completion.'],
 'edf_native_frame_dispatch_tests',
 ['Do not remove compatibility routes simply to make original-call counts zero.', 'Do not change unrelated defaults to force a fixture through the desired path.'],
 'If support policy or callee effects are absent, leave the fallback intact and return that exact prerequisite.')

card('R10.trace','implementation',
 'src/native_graphics/native_frame_dispatch.h src/native_graphics/guest_shader_bridge.cpp tools/summarize-renderer-coverage-run.py out/renderer-inventory/indirect-site-ledger.csv tests/native_frame_dispatch_tests.cpp',
 'ResolveIndirectFunction|HookTiming|RenderOverlay|RenderPose',
 'Instrument the outer callback at821A5158 with instruction/target/receiver and scenario identity, using a bounded collector.',
 'R01.callbacks supplies the selected site/receiver contract; instrumentation of an unresolved target is allowed, but must label it unresolved rather than assuming a class.',
 ['Define a trace row with schema version, run/scenario ID, timestamp, frame/publication ID, instruction, target, receiver/vtable, backend/pass and fallback reason.',
  'Record at the actual dispatch/branch, not only an enclosing timing scope. Bound memory/events and expose dropped/sampled counts.',
  'Join observed sites/targets to static ledgers; retain unknowns with their raw locators and emit a new-work list.',
  'Test known/unknown target and collector overflow, then capture one scenario interval and verify attribution before broadening to family/pass events.'],
 ['A changed target at the same callsite is preserved as a distinct observation.', 'Overflow/sampling is reported and cannot masquerade as complete target coverage.', 'Every event joins to a known row or an explicit new-target investigation.'],
 'edf_native_frame_dispatch_tests',
 ['Do not log every draw without a bound and then use the run for performance measurement.', 'Do not treat timing phase names as exact callback receiver proof.'],
 'If a site lacks a stable frame/scenario identifier, record the missing correlation and do not claim scenario attribution.')

card('R10.capture','implementation',
 'src/native_graphics/native_backend_host.cpp src/native_graphics/native_host_surface.cpp src/native_graphics/native_capture_policy.h tests/native_backend_host_tests.cpp tests/native_capture_policy_tests.cpp',
 'captured_|edf_native_host_capture|Capture|sequence_',
 'Extend the final-host capture policy to request exactly three images with distinct timestamps/sequence IDs; keep the existing one-shot behavior as the default.',
 'No other task must be complete. Read both backend-host and D3D11-host capture paths and retain their final-composition semantics.',
 ['Locate when each host path captures relative to UI composition and presentation; identify the published sequence and resource lifetime at that point.',
  'Implement a bounded capture schedule/count and unique output naming. Define handling for repeated sequence IDs, missing images, write errors and overwrite attempts.',
  'Write a manifest containing capture index, wall/monotonic time, sequence, extent/backend and complete-versus-partial kind. Avoid changing normal behavior when capture is off.',
  'Add policy/host tests and collect before/during/after gameplay and pause/loading examples; verify actual UI composition visually.'],
 ['Exactly the configured bounded number of files is produced; existing files are not silently overwritten.', 'Manifest sequence/time matches the captured final host frame, including repeated images.', 'Disabled capture causes no readback/file activity; old one-shot configuration still works.'],
 'edf_native_capture_policy_tests edf_native_backend_host_tests',
 ['Do not repurpose partial scene-output BMPs and label them complete.', 'Do not require a visible OS main window for automated GPU capture.'],
 'If a backend cannot expose final composition or sequence identity, report that limitation explicitly and leave its acceptance open.')

card('R10.input','implementation',
 'src/scripted_input.h src/scripted_input_logic.h tools/renderer-coverage-input.txt tests/scripted_input_reload_tests.cpp docs/renderer-coverage-runtime.md',
 'GetDeviceState|ReloadInputEvents|t0_|ButtonsAt|AnalogAt',
 'Add one wait-for-gameplay-ready action followed by a short movement event, while preserving the existing time-only script format.',
 'R10.trace must provide or identify a trustworthy gameplay/control-ready event. Merely seeing a rendered scene is insufficient because the intro renders before control is available.',
 ['Define readiness from an audited game/control state and record its provenance. Keep waiting bounded with a visible timeout result.',
  'Schedule dependent actions relative to the actual readiness event; record intended time, actual poll time, scenario and release time.',
  'Preserve old scripts, live reload clock semantics, neutral expiry and real-pad merging; do not replay expired events after a reload.',
  'Add delayed-ready/no-ready/reload tests, then verify a movement or fire action by resulting state/captures, not just delivered buttons.'],
 ['A late readiness event shifts dependent controls instead of losing them during a cutscene.', 'No readiness before deadline reports not-reached and leaves controls neutral.', 'Reload and expiry do not latch buttons/axes or restart the scenario clock.'],
 'edf_scripted_input_tests',
 ['Do not change the player control scheme to make one script work.', 'Do not use a fixed180-second delay as proof of gameplay readiness.'],
 'If no validated control-ready marker is available, deliver the candidate field/producer investigation instead of inventing a timer heuristic.')

card('R10.scenarios','runtime-validation',
 'docs/renderer-coverage-scenario-results.json docs/renderer-coverage-runtime.md tools/start-native-binding-validation.ps1 tools/renderer-coverage-input.txt tools/summarize-renderer-coverage-run.py',
 'S01|S02|S03|S04|S05|S06|S07|S08|S09|S10|S11|S12|S13',
 'Repeat S03/S04 using readiness, route attribution and complete-frame burst artifacts before selecting an unvisited scenario.',
 'R10.trace, R10.capture and R10.input must provide their selected-scenario evidence. A matched reference is required for parity; otherwise report execution only.',
 ['Select one scenario and list its required mode, map/content, controls, observation markers and pass/fail conditions before launching.',
  'Use isolated userdata and a new output directory. Record executable/source hashes, exact arguments, input file and machine/backend information.',
  'Run bounded controls and collect reached-state, route, complete-frame and resource evidence. Stop only the owned process after verifying its actual executable path.',
  'Compare with the reference, assign reached/observed/compared status separately, add new gaps, and update only the supported scenario conclusions. Repeat across the content census.'],
 ['Every claimed action has an actual reached marker and observed effect.', 'Missing families/modes or unavailable references remain explicit untested cases.', 'Each failure/new target has a task and artifacts sufficient to reproduce it.'],
 '',
 ['Do not infer all-map coverage from Mission1.', 'Do not kill an existing user game process or reuse output paths that would overwrite evidence.'],
 'If assets, readiness, input or reference prerequisites fail, record not-reached/not-compared and resolve the named prerequisite before treating the scenario as accepted.')

card('R10.cadence','implementation',
 'src/native_graphics/native_pacing.h src/native_graphics/native_frame_flight.h src/native_graphics/native_queued_scene.h src/native_graphics/guest_shader_bridge.cpp tools/report-native-host-cadence.py',
 'simulation|generation|interpol|FrameExtraSimulationSteps|render_helper',
 'Use a deterministic fixture with a60Hz producer and120Hz consumer rendering one complete retained publication without guest render callbacks.',
 'For the selected mode, R04.pass/R06.families/R07.effects/R07.environment/R07.shadows/R08.ui/R08.loading/R08.movie/R08.present must provide complete consumer and lifetime contracts. Do not integrate partial content and call full-frame independence complete.',
 ['Write the producer-publication-consumer-retirement state machine, including missed ticks, interpolation endpoints, pause and loading transitions.',
  'Schedule render consumption independently while preserving exactly one authoritative simulation update per tick; interpolate only approved render inputs.',
  'Guard all original consumer entries for the selected supported mode and retain input generations until every consuming GPU frame finishes.',
  'Test delayed producer/consumer and transitions, then measure produced publication IDs, rendered unique images and presented sequences in gameplay.'],
 ['A60Hz simulation remains60Hz when render cadence changes to120Hz.', 'Extra frames show measured interpolation/image changes where expected, rather than repeated Present of one image.', 'Pause/load/consumer lag preserves simulation authority and resource lifetime without original consumer reentry.'],
 'edf_native_pacing_tests edf_native_scene_tests edf_native_host_lifetime_tests',
 ['Do not increase simulation speed to reach a rendering target.', 'Do not claim120Hz from an FPS cap or presentation count alone.'],
 'If any required content still needs an original consumer callback, leave full-frame integration incomplete and identify that specific upstream task.')

card('R10.performance','runtime-validation',
 'tools/report-native-host-cadence.py tools/report-native-frame-trace.py tools/report-native-geometry-runs.py tools/start-native-binding-validation.ps1 docs/native-backend-migration.md',
 'edf_native_geometry_workers|edf_native_frame_latency|edf_native_msaa|edf_native_vsync',
 'Measure one fixed gameplay route on D3D12 with default settings and diagnostics/capture disabled; establish a reproducible baseline before changing one variable.',
 'R10.cadence provides the mode being assessed, R10.scenarios provides a repeatable route and accepted content. Record the actual machine/display configuration.',
 ['Define warmup and measurement intervals, deterministic route, power/display settings and required metrics before running.',
  'Collect CPU/GPU and frame-time distribution, unique image cadence, memory peak and failures with intrusive audit tracing/readback disabled.',
  'Compare backend, worker0/1/4, sample count, native resolution and credits using a documented pairwise matrix; change one factor for causal comparisons.',
  'Report medians and tail percentiles, durations/sample counts, visual checks and limitations. Separate regression from a target the implementation never met.'],
 ['Reported intervals exclude startup/warmup and identify instrumentation overhead.', '120Hz claims include unique-image cadence and preserved simulation, not only presentation rate.', 'Each comparison names backend/settings, content route and sample size; unsupported combinations are explicit.'],
 '',
 ['Do not use the35.6FPS capture-heavy audit run as a performance baseline.', 'Do not average away stalls or silently discard failed runs.'],
 'If the route cannot repeat or timing instrumentation changes behavior materially, report the measurement limitation and fix it before drawing a performance conclusion.')
