"""One allowlist shared by the offline runner and dispatch acceptance gate."""
CPU = """edf_renderer_scalar_contract_tests edf_renderer_scalar_analysis_tests
edf_renderer_scalar_pipeline_tests edf_renderer_scalar_effects_tests
edf_renderer_setter_contract_tests edf_renderer_setter_analysis_tests
edf_native_frame_dispatch_tests edf_native_shader_binding_tests
edf_native_material_render_state_tests edf_native_material_sampler_tests
edf_native_capture_policy_tests edf_native_pacing_tests edf_scripted_input_tests
edf_native_backend_tests edf_native_upload_ring_tests edf_native_decode_worker_tests
edf_native_effect_tests edf_native_display_gamma_tests
edf_native_worker_callback_audit_tests edf_native_model_constructor_tests""".split()
RENDER = """edf_native_scene_tests edf_native_backend_completion_tests
edf_native_backend_ui_tests edf_native_backend_compositor_tests
edf_native_backend_conformance_tests edf_native_static_pass_replay_tests
edf_native_immediate_tail_tests""".split()
