# Writes the build identity header (edf_version_info.h) that src/version.cpp includes.
# Runs on every build (CMakeLists.txt edf_version_info) and rewrites the header only
# when its contents change, so an unchanged commit recompiles nothing.
#   cmake -DSOURCE_DIR=<repo> -DOUTPUT=<header> -DVERSION=<x.y.z[-pre]> -P write-version.cmake
if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUTPUT OR NOT DEFINED VERSION)
    message(FATAL_ERROR "write-version.cmake needs SOURCE_DIR, OUTPUT and VERSION")
endif()
include(${CMAKE_CURRENT_LIST_DIR}/version-info.cmake)
edf_git_identity("${SOURCE_DIR}" hash dirty)
edf_version_full("${VERSION}" "${hash}" "${dirty}" full)
set(content "// Generated by tools/write-version.cmake. Do not edit.
#pragma once
#define EDF2027_VERSION \"${VERSION}\"
#define EDF2027_GIT_HASH \"${hash}\"
#define EDF2027_GIT_DIRTY ${dirty}
#define EDF2027_VERSION_FULL \"${full}\"
")
set(previous "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
endif()
if(NOT previous STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
